### ISSUE TITLE
扩展 API 实现自有数据的读取,报错,搞不清楚哪里出错,帮忙看下.

### ISSUE THREAD

**Issue by myz8110** [ricequant/rqalpha#113]
## 4. 在C:\Anaconda3\Lib\site-packages\rqalpha\mod目录下有min20limit_day.csv文件和rqalpha_mod_extend_api_demo.py,代码如下:

```
import os
import pandas as pd
from rqalpha.interface import AbstractMod


__config__ = {
    "csv_path": None
}


def load_mod():
    return ExtendAPIDemoMod()


class ExtendAPIDemoMod(AbstractMod):
    def __init__(self):
        # 注入API 一定要在初始化阶段，否则无法成功注入
            self._csv_path = None
            self._inject_api()
    def start_up(self, env, mod_config):
            self._csv_path = os.path.abspath(os.path.join(os.path.dirname(__file__), mod_config.csv_path))

    def tear_down(self, code, exception=None):
            pass

    def _inject_api(self):
        from rqalpha import export_as_api
        from rqalpha.execution_context import ExecutionContext
        from rqalpha.const import EXECUTION_PHASE

        @export_as_api
        @ExecutionContext.enforce_phase(EXECUTION_PHASE.ON_INIT,
                                        EXECUTION_PHASE.BEFORE_TRADING,
                                        EXECUTION_PHASE.ON_BAR,
                                        EXECUTION_PHASE.AFTER_TRADING,
                                        EXECUTION_PHASE.SCHEDULED)
        def get_csv_as_df():
            data = pd.read_csv(self._csv_path)
            return data
```

## 5.在C:\Anaconda3\examples目录下有demo.py,代码如下:

```
from rqalpha.api import *


def init(context):
    IF1706_df = get_csv_as_df()
    context.IF1706_df = IF1706_df


def before_trading(context):
    logger.info(context.IF1706_df)


__config__ = {
    "base": {
        "securities": "future",
        "start_date": "2015-01-09",
        "end_date": "2015-01-10",
        "frequency": "1d",
        "matching_type": "current_bar",
        "future_starting_cash": 1000000,
        "benchmark": None,
    },
    "extra": {
        "log_level": "verbose",
    },
    "mod": {
        "extend_api_demo": {
            "enabled": True,
            "lib": "rqalpha.mod.rqalpha_mod_extend_api_demo",
            "csv_path": "../min20limit_day.csv"
        }
    }
}
```

## 6.报错如下:

```
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Anaconda3\examples>rqalpha run -f demo.py
[2017-05-02 15:09:43.406995] DEBUG: system_log:
{'base': {'account_list': [ACCOUNT_TYPE.FUTURE],
 'benchmark': None,
 'data_bundle_path': 'C:\\Users\\Administrator\\.rqalpha\\./bundle',
 'end_date': datetime.date(2015, 1, 10),
 'frequency': '1d',
 'future_starting_cash': 1000000,
 'handle_split': False,
 'margin_multiplier': 1,
 'matching_type': 'current_bar',
 'persist': False,
 'persist_mode': PERSIST_MODE.REAL_TIME,
 'resume_mode': False,
 'run_type': RUN_TYPE.BACKTEST,
 'securities': 'future',
 'start_date': datetime.date(2015, 1, 9),
 'stock_starting_cash': 100000,
 'strategy_file': 'demo.py'},
 'extra': {'context_vars': None,
 'enable_profiler': False,
 'force_run_init_when_pt_resume': False,
 'is_hold': False,
 'locale': 'cn',
 'log_level': 'verbose',
 'user_system_log_disabled': False},
 'mod': {'extend_api_demo': {'csv_path': '../min20limit_day.csv',
 'enabled': True,
 'lib': 'rqalpha.mod.rqalpha_mod_extend_api_demo'},
 'h_world': {'enabled': True, 'lib': 'rqalpha.mod.hello_world', 'priority': 100}
,
 'sys_analyser': {'enabled': True},
 'sys_funcat': {'enabled': False},
 'sys_progress': {'enabled': True, 'show': False},
 'sys_risk': {'enabled': True, 'validate_position': True},
 'sys_simulation': {'enabled': True, 'signal': False},
 'sys_stock_realtime': {'enabled': False}},
 'validator': {'cash_return_by_stock_delisted': False, 'close_amount': True},
 'version': '0.1.5',
 'whitelist': ['base', 'extra', 'validator', 'mod']}
[2017-05-02 15:09:43.409995] DEBUG: system_log: 载入 Mod rqalpha.mod.rqalpha_mod
_sys_simulation
[2017-05-02 15:09:43.423996] DEBUG: system_log: 载入 Mod rqalpha.mod.rqalpha_mod
_sys_progress
[2017-05-02 15:09:43.425996] DEBUG: system_log: 载入 Mod rqalpha.mod.rqalpha_mod
_sys_risk
[2017-05-02 15:09:43.431996] DEBUG: system_log: 载入 Mod rqalpha.mod.rqalpha_mod
_sys_analyser
[2017-05-02 15:09:43.433996] DEBUG: system_log: 载入 Mod rqalpha.mod.hello_world

[2017-05-02 15:09:43.435996] DEBUG: system_log: 载入 Mod rqalpha.mod.rqalpha_mod
_extend_api_demo
Traceback (most recent call last):
  File "c:\anaconda3\lib\site-packages\rqalpha\main.py", line 190, in run
    mod_handler.set_env(env)
    [36m��                   �� <rqalpha.environment.Environment object at 0x00
000000047BBA20>[m
    [36m�� <rqalpha.mod.ModHandler object at 0x0000000004CEB668>[m
  File "c:\anaconda3\lib\site-packages\rqalpha\mod\__init__.py", line 55, in set
_env
    mod = mod_module.load_mod()
    [36m��     �� <module 'rqalpha.mod.rqalpha_mod_extend_api_demo' from 'c:\\a
naconda3\\lib\\site-packages\\rqalpha\\mod\\rqalpha_mod_extend_api_...[m
    [36m�� <rqalpha.mod.hello_world.HelloWorldMod object at 0x00000000048301D0>
[m
  File "c:\anaconda3\lib\site-packages\rqalpha\mod\rqalpha_mod_extend_api_demo.p
y", line 12, in load_mod
    [33;1mreturn[m ExtendAPIDemoMod()
    [36m       �� <class 'rqalpha.mod.rqalpha_mod_extend_api_demo.ExtendAPIDemo
Mod'>[m
  File "c:\anaconda3\lib\site-packages\rqalpha\mod\rqalpha_mod_extend_api_demo.p
y", line 19, in __init__
    self._inject_api()
    [36m�� <rqalpha.mod.rqalpha_mod_extend_api_demo.ExtendAPIDemoMod object at
0x0000000004837198>[m
  File "c:\anaconda3\lib\site-packages\rqalpha\mod\rqalpha_mod_extend_api_demo.p
y", line 28, in _inject_api
    from rqalpha import export_as_api
ImportError: cannot import name 'export_as_api'
0000-00-00 ERROR cannot import name 'export_as_api'
[2017-05-02 15:09:43.594005] ERROR: system_log: 策略运行产生异常
Traceback (most recent call last):
  File "c:\anaconda3\lib\site-packages\rqalpha\main.py", line 190, in run
    mod_handler.set_env(env)
  File "c:\anaconda3\lib\site-packages\rqalpha\mod\__init__.py", line 55, in set
_env
    mod = mod_module.load_mod()
  File "c:\anaconda3\lib\site-packages\rqalpha\mod\rqalpha_mod_extend_api_demo.p
y", line 12, in load_mod
    return ExtendAPIDemoMod()
  File "c:\anaconda3\lib\site-packages\rqalpha\mod\rqalpha_mod_extend_api_demo.p
y", line 19, in __init__
    self._inject_api()
  File "c:\anaconda3\lib\site-packages\rqalpha\mod\rqalpha_mod_extend_api_demo.p
y", line 28, in _inject_api
    from rqalpha import export_as_api
ImportError: cannot import name 'export_as_api'
Traceback (most recent call last):
  File "c:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\lib\runpy.py", line 85, in _run_code
    [35;1mexec[m(code, run_globals)
    [36m     ��     �� {'__name__': '__main__', '__doc__': None, '__package__':
 '', '__loader__': <zipimporter object "C:\Anaconda3\Scripts\rqalpha.exe...[m
    [36m     �� <code object <module> at 0x000000000279A780, file "C:\Anaconda3
\Scripts\rqalpha.exe\__main__.py", line 2>[m
  File "C:\Anaconda3\Scripts\rqalpha.exe\__main__.py", line 9, in <module>
    sys.exit(entry_point())
    [36m��        �� <function entry_point at 0x00000000029DE598>[m
    [36m�� <module 'sys' (built-in)>[m
  File "c:\anaconda3\lib\site-packages\rqalpha\__main__.py", line 66, in entry_p
oint
    cli(obj={})
    [36m�� <click.core.Group object at 0x0000000005AB0F98>[m
  File "c:\anaconda3\lib\site-packages\click\core.py", line 722, in __call__
    [33;1mreturn[m self.main(*args, **kwargs)
    [36m       ��          ��       �� {'obj': {'VERBOSE': 0}}[m
    [36m       ��          �� ()[m
    [36m       �� <click.core.Group object at 0x0000000005AB0F98>[m
  File "c:\anaconda3\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
    [36m     ��           �� <click.core.Context object at 0x0000000005AD1588>
[m
    [36m     �� <click.core.Group object at 0x0000000005AB0F98>[m
  File "c:\anaconda3\lib\site-packages\click\core.py", line 1066, in invoke
    [33;1mreturn[m _process_result(sub_ctx.command.invoke(sub_ctx))
    [36m       ��               ��                      �� <click.core.Context
object at 0x00000000029A79E8>[m
    [36m       ��               �� <click.core.Context object at 0x00000000029A
79E8>[m
    [36m       �� <function MultiCommand.invoke.<locals>._process_result at 0x0
0000000027867B8>[m
  File "c:\anaconda3\lib\site-packages\click\core.py", line 895, in invoke
    [33;1mreturn[m ctx.invoke(self.callback, **ctx.params)
    [36m       ��          ��                �� <click.core.Context object at 0
x00000000029A79E8>[m
    [36m       ��          �� <click.core.Command object at 0x0000000005AD1080>
[m
    [36m       �� <click.core.Context object at 0x00000000029A79E8>[m
  File "c:\anaconda3\lib\site-packages\click\core.py", line 535, in invoke
    [33;1mreturn[m callback(*args, **kwargs)
    [36m       ��         ��       �� {'base__strategy_file': 'demo.py', 'base_
_data_bundle_path': None, 'base__start_date': None, 'base__end_date': None, 'bas
e__stoc...[m
    [36m       ��         �� ()[m
    [36m       �� <function run at 0x0000000005ACC510>[m
  File "c:\anaconda3\lib\site-packages\rqalpha\__main__.py", line 118, in run
    main.run(parse_config(kwargs, config_path))
    [36m��        ��            ��       �� None[m
    [36m��        ��            �� {'base__strategy_file': 'demo.py', 'base__da
ta_bundle_path': None, 'base__start_date': None, 'base__end_date': None, 'base__
stoc...[m
    [36m��        �� <function parse_config at 0x0000000005AC72F0>[m
    [36m�� <module 'rqalpha.main' from 'c:\\anaconda3\\lib\\site-packages\\rqal
pha\\main.py'>[m
  File "c:\anaconda3\lib\site-packages\rqalpha\main.py", line 323, in run
    mod_handler.tear_down(code, user_exc)
    [36m��                     ��     �� CustomException(cannot import name 'ex
port_as_api',)[m
    [36m��                     �� EXIT_CODE.EXIT_INTERNAL_ERROR[m
    [36m�� <rqalpha.mod.ModHandler object at 0x0000000004CEB668>[m
  File "c:\anaconda3\lib\site-packages\rqalpha\mod\__init__.py", line 72, in tea
r_down
    ret = self._mod_dict[mod_name].tear_down(*args)
    [36m      ��              ��                    �� (EXIT_CODE.EXIT_INTERNAL
_ERROR, CustomException(cannot import name 'export_as_api',))[m
    [36m      ��              �� 'extend_api_demo'[m
    [36m      �� <rqalpha.mod.ModHandler object at 0x0000000004CEB668>[m
KeyError: 'extend_api_demo'

```

**Comment by wh1100717** [comment]
@myz8110 请使用最新版本 export_as_api 是从 2.1.0 才开始支持的。

详情请看 更新日志 [RQAlpha Changelog](http://rqalpha.io/zh_CN/latest/history.html#id3)

**Comment by myz8110** [comment]
@wh1100717  已更新,问题已解决,谢谢.
