### ISSUE TITLE
conda 环境下 最新安装 成功后, 运行策略 失败.

### ISSUE THREAD

**Issue by yssource** [ricequant/rqalpha#141]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

## 1. RQAlpha的版本
2.2.4
## 2. Python的版本
python 3.5
## 5. 您出现的错误堆栈日志信息

```
   rqalpha update_bundle                                                                                                                                                                             
尝试 http://7xjci3.com1.z0.glb.clouddn.com/bundles_v3/rqbundle_20170519.tar.bz2 ...
尝试 http://7xjci3.com1.z0.glb.clouddn.com/bundles_v3/rqbundle_20170518.tar.bz2 ...
下载中 ...  [####################################]  100%             
数据下载成功: /home/jimmy/.rqalpha/bundle

```

`   rqalpha run -fq 1d -rt b -f ./rqalpha/examples/buy_and_hold.py -sc 10000000 -l verbose -d ~/.rqalpha/bundle -s 2017-01-01 -e 2017-5-12 --benchmark 000300.XSHG --plot -o /tmp/d.pkl
`
```
[2017-05-19 23:28:11.760278] DEBUG: system_log: 
{'base': {'account_list': [ACCOUNT_TYPE.STOCK],
          'benchmark': '000300.XSHG',
          'data_bundle_path': '/home/jimmy/.rqalpha/bundle',
          'end_date': datetime.date(2017, 5, 12),
          'frequency': '1d',
          'future_starting_cash': 0,
          'margin_multiplier': 1,
          'persist': False,
          'persist_mode': PERSIST_MODE.REAL_TIME,
          'resume_mode': False,
          'run_type': RUN_TYPE.BACKTEST,
          'securities': ['stock'],
          'source_code': None,
          'start_date': datetime.date(2017, 1, 1),
          'stock_starting_cash': 10000000.0,
          'strategy_file': './rqalpha/examples/buy_and_hold.py'},
 'extra': {'context_vars': None,
           'enable_profiler': False,
           'force_run_init_when_pt_resume': False,
           'is_hold': False,
           'locale': 'cn',
           'log_level': 'verbose',
           'user_system_log_disabled': False},
 'mod': {'hello': {'enabled': False},
         'shipane': {'enabled': False},
         'sys_analyser': {'enabled': True,
                          'output_file': '/tmp/d.pkl',
                          'plot': True},
         'sys_funcat': {'enabled': True},
         'sys_progress': {'enabled': True, 'show': False},
         'sys_risk': {'enabled': True, 'validate_position': True},
         'sys_simulation': {'enabled': True, 'signal': False},
         'sys_stock_realtime': {'enabled': True}},
 'validator': {'cash_return_by_stock_delisted': False, 'close_amount': True},
 'version': '0.1.5',
 'whitelist': ['base', 'extra', 'validator', 'mod']}
[2017-05-19 23:28:11.760577] DEBUG: system_log: 载入 Mod rqalpha.mod.rqalpha_mod_sys_simulation
[2017-05-19 23:28:11.767497] DEBUG: system_log: 载入 Mod rqalpha.mod.rqalpha_mod_sys_stock_realtime
[2017-05-19 23:28:11.770352] DEBUG: system_log: 载入 Mod rqalpha.mod.rqalpha_mod_sys_risk
[2017-05-19 23:28:11.771786] DEBUG: system_log: 载入 Mod rqalpha.mod.rqalpha_mod_sys_progress
[2017-05-19 23:28:11.772285] DEBUG: system_log: 载入 Mod rqalpha.mod.rqalpha_mod_sys_analyser
[2017-05-19 23:28:11.773718] DEBUG: system_log: 载入 Mod rqalpha.mod.rqalpha_mod_sys_funcat
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/jimmy/anaconda3/envs/rqalpha/lib/python3.5/site-packages/better_exceptions/__init__.py", line 343, in excepthook
    formatted = format_exception(exc, value, tb)
  File "/home/jimmy/workspace/git/rqalpha/rqalpha/utils/logger.py", line 35, in format_exception
    formatted, colored_source = better_exceptions.format_traceback(tb)
  File "/home/jimmy/anaconda3/envs/rqalpha/lib/python3.5/site-packages/better_exceptions/__init__.py", line 307, in format_traceback
    formatted, colored = format_traceback_frame(tb)
  File "/home/jimmy/anaconda3/envs/rqalpha/lib/python3.5/site-packages/better_exceptions/__init__.py", line 267, in format_traceback_frame
    filename, lineno, function, source, color_source, relevant_values = get_traceback_information(tb)
  File "/home/jimmy/anaconda3/envs/rqalpha/lib/python3.5/site-packages/better_exceptions/__init__.py", line 260, in get_traceback_information
    relevant_values = get_relevant_values(source, tb.tb_frame, tree)
  File "/home/jimmy/anaconda3/envs/rqalpha/lib/python3.5/site-packages/better_exceptions/__init__.py", line 169, in get_relevant_values
    values.append((text, col, format_value(val)))
  File "/home/jimmy/anaconda3/envs/rqalpha/lib/python3.5/site-packages/better_exceptions/__init__.py", line 154, in format_value
    v = repr(v)
  File "/home/jimmy/anaconda3/envs/rqalpha/lib/python3.5/site-packages/bcolz/ctable.py", line 1275, in __repr__
    nbytes, cbytes, cratio = self._get_stats()
  File "/home/jimmy/anaconda3/envs/rqalpha/lib/python3.5/site-packages/bcolz/ctable.py", line 1265, in _get_stats
    column = cols[name]
  File "/home/jimmy/anaconda3/envs/rqalpha/lib/python3.5/site-packages/bcolz/ctable.py", line 60, in __getitem__
    return self._cols[name]
KeyError: 'date'

Original exception was:
Traceback (most recent call last):
  File "/home/jimmy/workspace/git/rqalpha/rqalpha/main.py", line 199, in run
    env.set_data_source(BaseDataSource(config.base.data_bundle_path))
  File "/home/jimmy/workspace/git/rqalpha/rqalpha/data/base_data_source.py", line 49, in __init__
    DayBarStore(_p('stocks.bcolz'), StockBarConverter),
  File "/home/jimmy/workspace/git/rqalpha/rqalpha/data/daybar_store.py", line 26, in __init__
    self._table = bcolz.open(main, 'r')
  File "/home/jimmy/anaconda3/envs/rqalpha/lib/python3.5/site-packages/bcolz/toplevel.py", line 131, in open
    return bcolz.ctable(rootdir=rootdir, mode=mode)
  File "/home/jimmy/anaconda3/envs/rqalpha/lib/python3.5/site-packages/bcolz/ctable.py", line 228, in __init__
    self.open_ctable()
  File "/home/jimmy/anaconda3/envs/rqalpha/lib/python3.5/site-packages/bcolz/ctable.py", line 327, in open_ctable
    self.cols.read_meta_and_open()
  File "/home/jimmy/anaconda3/envs/rqalpha/lib/python3.5/site-packages/bcolz/ctable.py", line 47, in read_meta_and_open
    self._cols[name] = bcolz.carray(rootdir=dir_, mode=self.mode)
  File "bcolz/carray_ext.pyx", line 1015, in bcolz.carray_ext.carray.__cinit__ (bcolz/carray_ext.c:13447)
  File "bcolz/carray_ext.pyx", line 1220, in bcolz.carray_ext.carray._open_carray (bcolz/carray_ext.c:16014)
  File "bcolz/carray_ext.pyx", line 702, in bcolz.carray_ext.chunks.__cinit__ (bcolz/carray_ext.c:9161)
RuntimeError: error decompressing the last chunk (error code: -1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jimmy/anaconda3/envs/rqalpha/bin/rqalpha", line 11, in <module>
    sys.exit(entry_point())
  File "/home/jimmy/workspace/git/rqalpha/rqalpha/__main__.py", line 49, in entry_point
    cli(obj={})
  File "/home/jimmy/anaconda3/envs/rqalpha/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/jimmy/anaconda3/envs/rqalpha/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/jimmy/anaconda3/envs/rqalpha/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jimmy/anaconda3/envs/rqalpha/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jimmy/anaconda3/envs/rqalpha/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/jimmy/workspace/git/rqalpha/rqalpha/__main__.py", line 113, in run
    main.run(cfg, source_code=source_code)
  File "/home/jimmy/workspace/git/rqalpha/rqalpha/main.py", line 316, in run
    code = _exception_handler(user_exc)
  File "/home/jimmy/workspace/git/rqalpha/rqalpha/main.py", line 322, in _exception_handler
    better_exceptions.excepthook(e.error.exc_type, e.error.exc_val, e.error.exc_tb)
  File "/home/jimmy/anaconda3/envs/rqalpha/lib/python3.5/site-packages/better_exceptions/__init__.py", line 343, in excepthook
    formatted = format_exception(exc, value, tb)
  File "/home/jimmy/workspace/git/rqalpha/rqalpha/utils/logger.py", line 35, in format_exception
    formatted, colored_source = better_exceptions.format_traceback(tb)
  File "/home/jimmy/anaconda3/envs/rqalpha/lib/python3.5/site-packages/better_exceptions/__init__.py", line 307, in format_traceback
    formatted, colored = format_traceback_frame(tb)
  File "/home/jimmy/anaconda3/envs/rqalpha/lib/python3.5/site-packages/better_exceptions/__init__.py", line 267, in format_traceback_frame
    filename, lineno, function, source, color_source, relevant_values = get_traceback_information(tb)
  File "/home/jimmy/anaconda3/envs/rqalpha/lib/python3.5/site-packages/better_exceptions/__init__.py", line 260, in get_traceback_information
    relevant_values = get_relevant_values(source, tb.tb_frame, tree)
  File "/home/jimmy/anaconda3/envs/rqalpha/lib/python3.5/site-packages/better_exceptions/__init__.py", line 169, in get_relevant_values
    values.append((text, col, format_value(val)))
  File "/home/jimmy/anaconda3/envs/rqalpha/lib/python3.5/site-packages/better_exceptions/__init__.py", line 154, in format_value
    v = repr(v)
  File "/home/jimmy/anaconda3/envs/rqalpha/lib/python3.5/site-packages/bcolz/ctable.py", line 1275, in __repr__
    nbytes, cbytes, cratio = self._get_stats()
  File "/home/jimmy/anaconda3/envs/rqalpha/lib/python3.5/site-packages/bcolz/ctable.py", line 1265, in _get_stats
    column = cols[name]
  File "/home/jimmy/anaconda3/envs/rqalpha/lib/python3.5/site-packages/bcolz/ctable.py", line 60, in __getitem__
    return self._cols[name]
KeyError: 'date'

```

**Comment by cedricporter** [comment]
这个估计是 bundle 损坏了，你再重新 `rqalpha update_bundle` 试试？

**Comment by yssource** [comment]
Thanks.
感觉是 `conda install bcolz` 带来的问题.
彻底删除 bcolz, `pip install bcolz` , 现在运行策略成功了.
