### ISSUE TITLE
current_snapshot()方法报错'NoneType' object has no attribute 'year'

### ISSUE THREAD

**Issue by cfz87862529** [ricequant/rqalpha#151]
## 1. RQAlpha的版本
2.2.7

## 2. Python的版本
3.6.1

## 3. 是Windows/Linux/MacOS or others?
Windows

## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置

```python
logger.info(current_snapshot('000001.XSHE'))
```

## 5. 您出现的错误堆栈日志信息

```python
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\rqalpha\core\strategy.py", line 84, in handle_bar
    self._handle_bar(self._user_context, bar_dict)
  File "F:/MyExplore/Python/rqalphaDemo/examples/cfz_test02.py", line 47, in handle_bar
    logger.info(current_snapshot('000001.XSHE'))
  File "C:\ProgramData\Anaconda3\lib\site-packages\rqalpha\execution_context.py", line 106, in wrapper
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\rqalpha\utils\arg_checker.py", line 378, in api_rule_check_wrapper
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\rqalpha\api\api_base.py", line 822, in current_snapshot
    return env.data_proxy.current_snapshot(order_book_id, frequency, env.calendar_dt)
  File "C:\ProgramData\Anaconda3\lib\site-packages\rqalpha\data\data_proxy.py", line 160, in current_snapshot
    d['prev_close'] = self._get_prev_close(order_book_id, dt)
  File "C:\ProgramData\Anaconda3\lib\site-packages\rqalpha\data\data_proxy.py", line 96, in _get_prev_close
    skip_suspended=False, include_now=False)
  File "C:\ProgramData\Anaconda3\lib\site-packages\rqalpha\data\base_data_source.py", line 176, in history_bars
    fields, adjust_type, adjust_orig)
  File "C:\ProgramData\Anaconda3\lib\site-packages\rqalpha\data\adjust.py", line 45, in adjust_bars
    adjust_orig_dt = np.uint64(convert_date_to_int(adjust_orig))
  File "C:\ProgramData\Anaconda3\lib\site-packages\rqalpha\utils\datetime_func.py", line 52, in convert_date_to_int
    t = dt.year * 10000 + dt.month * 100 + dt.day
AttributeError: 'NoneType' object has no attribute 'year'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\rqalpha\main.py", line 294, in run
    Executor(env).run(bar_dict)
  File "C:\ProgramData\Anaconda3\lib\site-packages\rqalpha\core\executor.py", line 65, in run
    event_bus.publish_event(event)
  File "C:\ProgramData\Anaconda3\lib\site-packages\rqalpha\events.py", line 43, in publish_event
    if l(event):
  File "C:\ProgramData\Anaconda3\lib\site-packages\rqalpha\utils\__init__.py", line 180, in wrapper
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\rqalpha\core\strategy.py", line 84, in handle_bar
    self._handle_bar(self._user_context, bar_dict)
  File "C:\ProgramData\Anaconda3\lib\site-packages\rqalpha\execution_context.py", line 95, in __exit__
    raise user_exc
rqalpha.utils.exception.CustomException: 'NoneType' object has no attribute 'year'
```

**Comment by hzliu** [comment]
给一下能完整重现的 bug 的策略？

**Comment by hzliu** [comment]
无反馈关闭
