### ISSUE TITLE
RQAlpha2.2.7源代码运行buy_and_hold.py脚本报错

### ISSUE THREAD

**Issue by luhouxiang** [ricequant/rqalpha#159]
## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置：
pycharm配置：

```
Script: E:\work\python3\rqalpha\rqalpha-script.py
Script parameters: run -f E:\work\python3\rqalpha\rqalpha\examples\buy_and_hold.py -d C:/Users/Administrator/.rqalpha/bundle/ -s 2016-06-01 -e 2016-12-01 --stock-starting-cash 100000
Python interpreter: Python 3.5.2(C:\Program Files\Anaconda3\envs\python35\python.exe
Working directory: E:\work\python3\rqalpha
```

代码结构：E:\work\python3\rqalpha
**rqalpha-script.py**由来：下载2.2.7版本，运行E:\work\python3\rqalpha>python setup.py install在目录C:\Program Files\Anaconda3\envs\python35\Scripts下生成，拷贝至E:\work\python3\rqalpha

测试代码：2.2.7自带脚本：buy_and_hold.py

另外：早前用0.3的版本使用源码调试是没问题的，那个代码是之前从github上下载的，后来升级后先是提示数据不对，利用命令：rqalpha update_bundle升级成功

## 5. 您出现的错误堆栈日志信息

```
"C:\Program Files\Anaconda3\envs\python35\python.exe" "C:\Program Files\JetBrains\PyCharm 2017.1.3\helpers\pydev\pydevd.py" --multiproc --qt-support --client 127.0.0.1 --port 6736 --file E:/work/python3/rqalpha/rqalpha-script.py run -f E:\work\python3\rqalpha\rqalpha\examples\buy_and_hold.py -d C:/Users/Administrator/.rqalpha/bundle/ -s 2016-06-01 -e 2016-12-01 --stock-starting-cash 100000
warning: Debugger speedups using cython not found. Run '"C:\Program Files\Anaconda3\envs\python35\python.exe" "C:\Program Files\JetBrains\PyCharm 2017.1.3\helpers\pydev\setup_cython.py" build_ext --inplace' to build.
pydev debugger: process 9784 is connecting

Connected to pydev debugger (build 171.4424.42)
Error in sys.excepthook:
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\envs\python35\lib\site-packages\better_exceptions-0.1.8-py3.5.egg\better_exceptions\__init__.py", line 343, in excepthook
    formatted = format_exception(exc, value, tb)
  File "E:/work/python3/rqalpha\rqalpha\utils\logger.py", line 35, in format_exception
    formatted, colored_source = better_exceptions.format_traceback(tb)
  File "C:\Program Files\Anaconda3\envs\python35\lib\site-packages\better_exceptions-0.1.8-py3.5.egg\better_exceptions\__init__.py", line 307, in format_traceback
    formatted, colored = format_traceback_frame(tb)
  File "C:\Program Files\Anaconda3\envs\python35\lib\site-packages\better_exceptions-0.1.8-py3.5.egg\better_exceptions\__init__.py", line 267, in format_traceback_frame
    filename, lineno, function, source, color_source, relevant_values = get_traceback_information(tb)
  File "C:\Program Files\Anaconda3\envs\python35\lib\site-packages\better_exceptions-0.1.8-py3.5.egg\better_exceptions\__init__.py", line 260, in get_traceback_information
    relevant_values = get_relevant_values(source, tb.tb_frame, tree)
  File "C:\Program Files\Anaconda3\envs\python35\lib\site-packages\better_exceptions-0.1.8-py3.5.egg\better_exceptions\__init__.py", line 169, in get_relevant_values
    values.append((text, col, format_value(val)))
  File "C:\Program Files\Anaconda3\envs\python35\lib\site-packages\better_exceptions-0.1.8-py3.5.egg\better_exceptions\__init__.py", line 154, in format_value
    v = repr(v)
  File "C:\Program Files\Anaconda3\envs\python35\lib\site-packages\bcolz\ctable.py", line 1396, in __repr__
    nbytes, cbytes, cratio = self._get_stats()
  File "C:\Program Files\Anaconda3\envs\python35\lib\site-packages\bcolz\ctable.py", line 1386, in _get_stats
    column = cols[name]
  File "C:\Program Files\Anaconda3\envs\python35\lib\site-packages\bcolz\ctable.py", line 84, in __getitem__
    return self._cols[name]
KeyError: 'date'

Original exception was:
Traceback (most recent call last):
  File "E:/work/python3/rqalpha\rqalpha\main.py", line 199, in run
    env.set_data_source(BaseDataSource(config.base.data_bundle_path))
  File "E:/work/python3/rqalpha\rqalpha\data\base_data_source.py", line 49, in __init__
    DayBarStore(_p('stocks.bcolz'), StockBarConverter),
  File "E:/work/python3/rqalpha\rqalpha\data\daybar_store.py", line 26, in __init__
    self._table = bcolz.open(main, 'r')
  File "C:\Program Files\Anaconda3\envs\python35\lib\site-packages\bcolz\toplevel.py", line 137, in open
    return bcolz.ctable(rootdir=rootdir, mode=mode)
  File "C:\Program Files\Anaconda3\envs\python35\lib\site-packages\bcolz\ctable.py", line 253, in __init__
    self._open_ctable()
  File "C:\Program Files\Anaconda3\envs\python35\lib\site-packages\bcolz\ctable.py", line 351, in _open_ctable
    self.cols.read_meta_and_open()
  File "C:\Program Files\Anaconda3\envs\python35\lib\site-packages\bcolz\ctable.py", line 71, in read_meta_and_open
    self._cols[name] = bcolz.carray(rootdir=dir_, mode=self.mode)
  File "bcolz/carray_ext.pyx", line 1068, in bcolz.carray_ext.carray.__cinit__ (bcolz\carray_ext.c:14890)
  File "bcolz/carray_ext.pyx", line 1273, in bcolz.carray_ext.carray._open_carray (bcolz\carray_ext.c:17520)
  File "bcolz/carray_ext.pyx", line 755, in bcolz.carray_ext.chunks.__cinit__ (bcolz\carray_ext.c:10432)
RuntimeError: error decompressing the last chunk (error code: -1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2017.1.3\helpers\pydev\pydevd.py", line 1585, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm 2017.1.3\helpers\pydev\pydevd.py", line 1015, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2017.1.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/work/python3/rqalpha/rqalpha-script.py", line 11, in <module>
    load_entry_point('rqalpha==2.2.7', 'console_scripts', 'rqalpha')()
  File "E:/work/python3/rqalpha\rqalpha\__main__.py", line 63, in entry_point
    cli(obj={})
  File "C:\Program Files\Anaconda3\envs\python35\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Anaconda3\envs\python35\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Anaconda3\envs\python35\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Anaconda3\envs\python35\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Anaconda3\envs\python35\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "E:/work/python3/rqalpha\rqalpha\__main__.py", line 127, in run
    results = main.run(cfg, source_code=source_code)
  File "E:/work/python3/rqalpha\rqalpha\main.py", line 316, in run
    code = _exception_handler(user_exc)
  File "E:/work/python3/rqalpha\rqalpha\main.py", line 322, in _exception_handler
    better_exceptions.excepthook(e.error.exc_type, e.error.exc_val, e.error.exc_tb)
  File "C:\Program Files\Anaconda3\envs\python35\lib\site-packages\better_exceptions-0.1.8-py3.5.egg\better_exceptions\__init__.py", line 343, in excepthook
    formatted = format_exception(exc, value, tb)
  File "E:/work/python3/rqalpha\rqalpha\utils\logger.py", line 35, in format_exception
    formatted, colored_source = better_exceptions.format_traceback(tb)
  File "C:\Program Files\Anaconda3\envs\python35\lib\site-packages\better_exceptions-0.1.8-py3.5.egg\better_exceptions\__init__.py", line 307, in format_traceback
    formatted, colored = format_traceback_frame(tb)
  File "C:\Program Files\Anaconda3\envs\python35\lib\site-packages\better_exceptions-0.1.8-py3.5.egg\better_exceptions\__init__.py", line 267, in format_traceback_frame
    filename, lineno, function, source, color_source, relevant_values = get_traceback_information(tb)
  File "C:\Program Files\Anaconda3\envs\python35\lib\site-packages\better_exceptions-0.1.8-py3.5.egg\better_exceptions\__init__.py", line 260, in get_traceback_information
    relevant_values = get_relevant_values(source, tb.tb_frame, tree)
  File "C:\Program Files\Anaconda3\envs\python35\lib\site-packages\better_exceptions-0.1.8-py3.5.egg\better_exceptions\__init__.py", line 169, in get_relevant_values
    values.append((text, col, format_value(val)))
  File "C:\Program Files\Anaconda3\envs\python35\lib\site-packages\better_exceptions-0.1.8-py3.5.egg\better_exceptions\__init__.py", line 154, in format_value
    v = repr(v)
  File "C:\Program Files\Anaconda3\envs\python35\lib\site-packages\bcolz\ctable.py", line 1396, in __repr__
    nbytes, cbytes, cratio = self._get_stats()
  File "C:\Program Files\Anaconda3\envs\python35\lib\site-packages\bcolz\ctable.py", line 1386, in _get_stats
    column = cols[name]
  File "C:\Program Files\Anaconda3\envs\python35\lib\site-packages\bcolz\ctable.py", line 84, in __getitem__
    return self._cols[name]
KeyError: 'date'

Process finished with exit code 1
```

**Comment by wh1100717** [comment]
@luhouxiang 你有没有执行过 `rqalpha update_bundle` ? 感觉 bundle 是很早以前版本引起的？ 麻烦试一下更新数据源  看看还会报错吗？

**Comment by luhouxiang** [comment]
已经试过了，没调用rqalpha update_bundle之前报的是数据不兼容，数据升级成功后才报的这个堆椎错误。

**Comment by wh1100717** [comment]
@luhouxiang 还是建议你创建一个新的虚拟环境，按照安装文档 重新安装一遍，再尝试一下。

尽量通过 anaconda 创建虚拟环境来使用 rqalpha，避免因为别的环境依赖问题导致出现错误。

**Comment by luhouxiang** [comment]
问题解决，方法如下：删除早期的环境，重新安装即可。另外，特别注明，必须删除早期环境，不能多环境并存，否则在安装时会出现各种错误。从这个观点来看，安装conda只是在删除的时候方便，安装时很难实现多环境并存。

**Comment by wh1100717** [comment]
@luhouxiang  库之间的依赖，甚至不同版本之前的冲突可能会产生异常的问题，这也是为什么 强烈推荐使用创建独立的虚拟环境来运行不同的程序的原因。
