### ISSUE TITLE
通过mod扩展账户报错

### ISSUE THREAD

**Issue by lpty** [ricequant/rqalpha#182]
## 1. RQAlpha的版本
Current Version:  (3, 0, 2)

## 2. Python的版本
Python2.7

## 3. 是Windows/Linux/MacOS or others?
Ubuntu16.04LTS

## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
run -f test.py -d /root/.rqalpha/bundle/ -s 2015-01-01 --account fund 100000 --benchmark 000300.XSHG --plot
备注：fund为我自己扩展的账户类型

## 5. 您出现的错误堆栈日志信息
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rqalpha/main.py", line 213, in run
    env.portfolio = broker.get_portfolio()
    │               └ <rqalpha.mod.rqalpha_mod_sys_simulation.simulation_broker.SimulationBroker object at 0x7f6d8aa6e050>
    └ <rqalpha.environment.Environment object at 0x7f6da8a74290>
  File "/usr/local/lib/python2.7/dist-packages/rqalpha/mod/rqalpha_mod_sys_simulation/simulation_broker.py", line 51, in get_portfolio
    return init_portfolio(self._env)
           │              └ <rqalpha.mod.rqalpha_mod_sys_simulation.simulation_broker.SimulationBroker object at 0x7f6d8aa6e050>
           └ <function init_portfolio at 0x7f6d98df8488>
  File "/usr/local/lib/python2.7/dist-packages/rqalpha/mod/rqalpha_mod_sys_simulation/utils.py", line 51, in init_portfolio
    raise NotImplementedError
NotImplementedError
2017-08-08 ERROR 
[2017-08-08 14:37:10.971028] ERROR: system_log: 策略运行产生异常
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rqalpha/main.py", line 213, in run
    env.portfolio = broker.get_portfolio()
  File "/usr/local/lib/python2.7/dist-packages/rqalpha/mod/rqalpha_mod_sys_simulation/simulation_broker.py", line 51, in get_portfolio
    return init_portfolio(self._env)
  File "/usr/local/lib/python2.7/dist-packages/rqalpha/mod/rqalpha_mod_sys_simulation/utils.py", line 51, in init_portfolio
    raise NotImplementedError
NotImplementedErro

**Comment by lpty** [comment]
@wh1100717

**Comment by lpty** [comment]
按目前的逻辑，扩展账户还是得修改源码。
