### ISSUE TITLE
REDIS 行情数据

### ISSUE THREAD

**Issue by saynever2015** [ricequant/rqalpha#185]
尝试导入行情数据到redis时，出现如下错误，能帮忙看看吗？

(C:\Users\quantlearning\AppData\Local\Continuum\Anaconda3) C:\Users\quantlearning>rqalpha quotation_server redis://localhost
Traceback (most recent call last):
  File "c:\users\quantlearning\appdata\local\continuum\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\quantlearning\appdata\local\continuum\anaconda3\lib\runpy.py", line 85, in _run_code
    [35;1mexec[m(code, run_globals)
    [36m     ��     �� {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <zipimporter object "C:\Users\quantlearning\AppData\Local...[m
    [36m     �� <code object <module> at 0x0000020A8C8C4420, file "C:\Users\quantlearning\AppData\Local\Continuum\Anaconda3\Scripts\rqalpha.exe\__ma...[m
  File "C:\Users\quantlearning\AppData\Local\Continuum\Anaconda3\Scripts\rqalpha.exe\__main__.py", line 9, in <module>
    sys.exit(entry_point())
    [36m��        �� <function entry_point at 0x0000020A8F353840>[m
    [36m�� <module 'sys' (built-in)>[m
  File "c:\users\quantlearning\appdata\local\continuum\anaconda3\lib\site-packages\rqalpha\__main__.py", line 70, in entry_point
    cli(obj={})
    [36m�� <click.core.Group object at 0x0000020A8F334668>[m
  File "c:\users\quantlearning\appdata\local\continuum\anaconda3\lib\site-packages\click\core.py", line 722, in __call__
    [33;1mreturn[m self.main(*args, **kwargs)
    [36m       ��          ��       �� {'obj': {'VERBOSE': 0}}[m
    [36m       ��          �� ()[m
    [36m       �� <click.core.Group object at 0x0000020A8F334668>[m
  File "c:\users\quantlearning\appdata\local\continuum\anaconda3\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
    [36m     ��           �� <click.core.Context object at 0x0000020A8F3CDD68>[m
    [36m     �� <click.core.Group object at 0x0000020A8F334668>[m
  File "c:\users\quantlearning\appdata\local\continuum\anaconda3\lib\site-packages\click\core.py", line 1066, in invoke
    [33;1mreturn[m _process_result(sub_ctx.command.invoke(sub_ctx))
    [36m       ��               ��                      �� <click.core.Context object at 0x0000020A8F3CD748>[m
    [36m       ��               �� <click.core.Context object at 0x0000020A8F3CD748>[m
    [36m       �� <function MultiCommand.invoke.<locals>._process_result at 0x0000020A8C787C80>[m
  File "c:\users\quantlearning\appdata\local\continuum\anaconda3\lib\site-packages\click\core.py", line 895, in invoke
    [33;1mreturn[m ctx.invoke(self.callback, **ctx.params)
    [36m       ��          ��                �� <click.core.Context object at 0x0000020A8F3CD748>[m
    [36m       ��          �� <click.core.Command object at 0x0000020A8F3CDF60>[m
    [36m       �� <click.core.Context object at 0x0000020A8F3CD748>[m
  File "c:\users\quantlearning\appdata\local\continuum\anaconda3\lib\site-packages\click\core.py", line 535, in invoke
    [33;1mreturn[m callback(*args, **kwargs)
    [36m       ��         ��       �� {'redis_url': 'redis://localhost'}[m
    [36m       ��         �� ()[m
    [36m       �� <function quotation_server at 0x0000020A8FA2B268>[m
  File "c:\users\quantlearning\appdata\local\continuum\anaconda3\lib\site-packages\rqalpha\mod\rqalpha_mod_sys_stock_realtime\__init__.py", line 60, in quotation_server
    config = parse_config({}, verify_config=False)
    [36m         �� <function parse_config at 0x0000020A8F353598>[m
**TypeError: parse_config() got an unexpected keyword argument 'verify_config'**

**Comment by saynever2015** [comment]
我在两台笔记本上都遇到这个额问题，有谁能帮忙看下吗

**Comment by saynever2015** [comment]
是最近的parameter 的rename引起的吗？

**Comment by cedricporter** [comment]
您好，可以更新到 3.0.6 ，已经解决了

**Comment by saynever2015** [comment]
谢谢
