### ISSUE TITLE
rqalpha mod install安装报错

### ISSUE THREAD

**Issue by xiaoluffy** [ricequant/rqalpha#194]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

## 1. RQAlpha的版本
3.0.6
## 2. Python的版本
3.6.1
## 3. 是Windows/Linux/MacOS or others?
Linux(ubuntu 16.04)
## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
自定义模块安装时候报错, mod名为rqalpha-mod-test
在mod目录下执行:

> rqalpha mod install .

但是使用下面命令可以执行成功:

> rqalpha mod install -e .

## 5. 您出现的错误堆栈日志信息
$ rqalpha mod install .
Invalid requirement: 'rqalpha_mod_.'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/pip/_vendor/packaging/requirements.py", line 92, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/opt/anaconda3/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1617, in parseString
    raise exc
  File "/opt/anaconda3/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1607, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/opt/anaconda3/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/opt/anaconda3/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3376, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/opt/anaconda3/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1383, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/opt/anaconda3/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3164, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip._vendor.pyparsing.ParseException: Expected stringEnd (at char 11), (line:1, col:12)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/pip/req/req_install.py", line 82, in __init__
    req = Requirement(req)
  File "/opt/anaconda3/lib/python3.6/site-packages/pip/_vendor/packaging/requirements.py", line 96, in __init__
    requirement_string[e.loc:e.loc + 8]))
pip._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'_.'"

**Comment by cedricporter** [comment]
大佬提的这个bug过了那么久终于在 develop 已经修复了。 😓bdc77e6a32f563434bb8bb6180b437fd1b08ccda
