### ISSUE TITLE
plot_save_file throw error - OverflowError: signed integer is less than minimum

### ISSUE THREAD

**Issue by Elric-pp** [ricequant/rqalpha#204]
## 1. RQAlpha的版本
3.0.6
## 2. Python的版本
python3.5

## 3. 是Windows/Linux/MacOS or others?
Linux debian

## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
[project](https://github.com/Elric-pp/rqalpha-docker)
我配置了一个 docker container 跑 rqalpha，然而在跑测试 example 的时候，在 sys_analyser 配置 `plot_save_file` 的时候就会报以下错误

重现步骤：
1. make build -> make start -> make enter
2. python run_file_demo.py

## 5. 您出现的错误堆栈日志信息
```
[2017-10-29 10:17:21.557800] ERROR: system_log: tear down fail for sys_analyser
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/rqalpha/mod/__init__.py", line 74, in tear_down
    ret = self._mod_dict[mod_name].tear_down(*args)
  File "/usr/local/lib/python3.5/site-packages/rqalpha/mod/rqalpha_mod_sys_analyser/mod.py", line 277, in tear_down
    plot_result(result_dict, self._mod_config.plot, self._mod_config.plot_save_file)
  File "/usr/local/lib/python3.5/site-packages/rqalpha/mod/rqalpha_mod_sys_analyser/plot.py", line 189, in plot_result
    plt.savefig(fnmame, bbox_inches='tight')
  File "/usr/local/lib/python3.5/site-packages/matplotlib/pyplot.py", line 697, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/matplotlib/figure.py", line 1814, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/matplotlib/backend_bases.py", line 2208, in print_figure
    **kwargs)
  File "/usr/local/lib/python3.5/site-packages/matplotlib/backends/backend_agg.py", line 507, in print_png
    FigureCanvasAgg.draw(self)
  File "/usr/local/lib/python3.5/site-packages/matplotlib/backends/backend_agg.py", line 430, in draw
    self.figure.draw(self.renderer)
  File "/usr/local/lib/python3.5/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/matplotlib/figure.py", line 1295, in draw
    renderer, self, artists, self.suppressComposite)
  File "/usr/local/lib/python3.5/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/lib/python3.5/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/matplotlib/axes/_base.py", line 2399, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/usr/local/lib/python3.5/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/lib/python3.5/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/matplotlib/axis.py", line 1133, in draw
    ticks_to_draw = self._update_ticks(renderer)
  File "/usr/local/lib/python3.5/site-packages/matplotlib/axis.py", line 974, in _update_ticks
    tick_tups = list(self.iter_ticks())
  File "/usr/local/lib/python3.5/site-packages/matplotlib/axis.py", line 917, in iter_ticks
    majorLocs = self.major.locator()
  File "/usr/local/lib/python3.5/site-packages/matplotlib/dates.py", line 1054, in __call__
    self.refresh()
  File "/usr/local/lib/python3.5/site-packages/matplotlib/dates.py", line 1074, in refresh
    dmin, dmax = self.viewlim_to_dt()
  File "/usr/local/lib/python3.5/site-packages/matplotlib/dates.py", line 832, in viewlim_to_dt
    return num2date(vmin, self.tz), num2date(vmax, self.tz)
  File "/usr/local/lib/python3.5/site-packages/matplotlib/dates.py", line 441, in num2date
    return _from_ordinalf(x, tz)
  File "/usr/local/lib/python3.5/site-packages/matplotlib/dates.py", line 256, in _from_ordinalf
    dt = datetime.datetime.fromordinal(ix).replace(tzinfo=UTC)
OverflowError: signed integer is less than minimum
```

**Comment by qzm** [comment]
```shellscript
pip install -i https://pypi.tuna.tsinghua.edu.cn/simple pandas==0.20.0 
```
可以解决问题

**Comment by cedricporter** [comment]
因为 pandas 0.21.0 不太兼容 matplotlib 。现在更可以更新 RQAlpha  到 3.0.9 ，会限制 pandas 版本在我们测试过的范围内。
