### ISSUE TITLE
最新版本在pandas 0.21.0下运行出错

### ISSUE THREAD

**Issue by mepwang** [ricequant/rqalpha#207]
## 1. RQAlpha的版本
3.0.6
## 2. Python的版本
3.5
之前能够正常运行，这两天更新了pandas至0.21.0版本
## 3. 是Windows/Linux/MacOS or others?
Ubuntu 16.04，已安装全部更新
## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
rqalpha的buy_and_hold示例，使用--plot选项
## 5. 您出现的错误堆栈日志信息
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1553, in __call__
    return self.func(*args)
  File "/usr/lib/python3.5/tkinter/__init__.py", line 599, in callit
    func(*args)
  File "/home/mep/trade/venv/lib/python3.5/site-packages/matplotlib/backends/backend_tkagg.py", line 323, in idle_draw
    self.draw()
  File "/home/mep/trade/venv/lib/python3.5/site-packages/matplotlib/backends/backend_tkagg.py", line 304, in draw
    FigureCanvasAgg.draw(self)
  File "/home/mep/trade/venv/lib/python3.5/site-packages/matplotlib/backends/backend_agg.py", line 430, in draw
    self.figure.draw(self.renderer)
  File "/home/mep/trade/venv/lib/python3.5/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/mep/trade/venv/lib/python3.5/site-packages/matplotlib/figure.py", line 1295, in draw
    renderer, self, artists, self.suppressComposite)
  File "/home/mep/trade/venv/lib/python3.5/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/mep/trade/venv/lib/python3.5/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/mep/trade/venv/lib/python3.5/site-packages/matplotlib/axes/_base.py", line 2399, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/home/mep/trade/venv/lib/python3.5/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/mep/trade/venv/lib/python3.5/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/mep/trade/venv/lib/python3.5/site-packages/matplotlib/axis.py", line 1133, in draw
    ticks_to_draw = self._update_ticks(renderer)
  File "/home/mep/trade/venv/lib/python3.5/site-packages/matplotlib/axis.py", line 974, in _update_ticks
    tick_tups = list(self.iter_ticks())
  File "/home/mep/trade/venv/lib/python3.5/site-packages/matplotlib/axis.py", line 917, in iter_ticks
    majorLocs = self.major.locator()
  File "/home/mep/trade/venv/lib/python3.5/site-packages/matplotlib/dates.py", line 1054, in __call__
    self.refresh()
  File "/home/mep/trade/venv/lib/python3.5/site-packages/matplotlib/dates.py", line 1074, in refresh
    dmin, dmax = self.viewlim_to_dt()
  File "/home/mep/trade/venv/lib/python3.5/site-packages/matplotlib/dates.py", line 832, in viewlim_to_dt
    return num2date(vmin, self.tz), num2date(vmax, self.tz)
  File "/home/mep/trade/venv/lib/python3.5/site-packages/matplotlib/dates.py", line 441, in num2date
    return _from_ordinalf(x, tz)
  File "/home/mep/trade/venv/lib/python3.5/site-packages/matplotlib/dates.py", line 256, in _from_ordinalf
    dt = datetime.datetime.fromordinal(ix).replace(tzinfo=UTC)
OverflowError: signed integer is less than minimum
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1553, in __call__
    return self.func(*args)
  File "/home/mep/trade/venv/lib/python3.5/site-packages/matplotlib/backends/backend_tkagg.py", line 233, in resize
    self.show()
  File "/home/mep/trade/venv/lib/python3.5/site-packages/matplotlib/backends/backend_tkagg.py", line 304, in draw
    FigureCanvasAgg.draw(self)
  File "/home/mep/trade/venv/lib/python3.5/site-packages/matplotlib/backends/backend_agg.py", line 430, in draw
    self.figure.draw(self.renderer)
  File "/home/mep/trade/venv/lib/python3.5/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/mep/trade/venv/lib/python3.5/site-packages/matplotlib/figure.py", line 1295, in draw
    renderer, self, artists, self.suppressComposite)
  File "/home/mep/trade/venv/lib/python3.5/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/mep/trade/venv/lib/python3.5/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/mep/trade/venv/lib/python3.5/site-packages/matplotlib/axes/_base.py", line 2399, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/home/mep/trade/venv/lib/python3.5/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/mep/trade/venv/lib/python3.5/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/mep/trade/venv/lib/python3.5/site-packages/matplotlib/axis.py", line 1133, in draw
    ticks_to_draw = self._update_ticks(renderer)
  File "/home/mep/trade/venv/lib/python3.5/site-packages/matplotlib/axis.py", line 974, in _update_ticks
    tick_tups = list(self.iter_ticks())
  File "/home/mep/trade/venv/lib/python3.5/site-packages/matplotlib/axis.py", line 917, in iter_ticks
    majorLocs = self.major.locator()
  File "/home/mep/trade/venv/lib/python3.5/site-packages/matplotlib/dates.py", line 1054, in __call__
    self.refresh()
  File "/home/mep/trade/venv/lib/python3.5/site-packages/matplotlib/dates.py", line 1074, in refresh
    dmin, dmax = self.viewlim_to_dt()
  File "/home/mep/trade/venv/lib/python3.5/site-packages/matplotlib/dates.py", line 832, in viewlim_to_dt
    return num2date(vmin, self.tz), num2date(vmax, self.tz)
  File "/home/mep/trade/venv/lib/python3.5/site-packages/matplotlib/dates.py", line 441, in num2date
    return _from_ordinalf(x, tz)
  File "/home/mep/trade/venv/lib/python3.5/site-packages/matplotlib/dates.py", line 256, in _from_ordinalf
    dt = datetime.datetime.fromordinal(ix).replace(tzinfo=UTC)
OverflowError: signed integer is less than minimum

**Comment by Elric-pp** [comment]
我和你遇到了一样的问题，27 号那天我测试还可以，28 号就不行了，感觉会不会是因为数据问题。

**Comment by cisxin** [comment]
同样,退回0.20.0就好了

**Comment by mysl** [comment]
+1，0.20.0 is ok.

**Comment by qzm** [comment]
```shellscript
pip install -i https://pypi.tuna.tsinghua.edu.cn/simple pandas==0.20.0 
```
可以解决问题

**Comment by cedricporter** [comment]
因为 pandas 0.21.0 不太兼容 matplotlib 。现在更可以更新 RQAlpha  到 3.0.9 ，会限制 pandas 版本在我们测试过的范围内。
