### ISSUE TITLE
locale.Error: unsupported locale setting;  when running "rqalpha update_bundle"

### ISSUE THREAD

**Issue by xieyuheng** [ricequant/rqalpha#215]
Traceback (most recent call last):
  File "/usr/local/bin/rqalpha", line 11, in <module>
    sys.exit(entry_point())
    │        └ <function entry_point at 0x7f674e17f9d8>
    └ <module 'sys' (built-in)>
  File "/usr/local/lib/python3.6/site-packages/rqalpha/__main__.py", line 70, in entry_point
    cli(obj={})
    └ <click.core.Group object at 0x7f674e15cf60>
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
           │          │       └ {'obj': {'VERBOSE': 0}}
           │          └ ()
           └ <click.core.Group object at 0x7f674e15cf60>
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
         │           └ <click.core.Context object at 0x7f674ded4d68>
         └ <click.core.Group object at 0x7f674e15cf60>
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │                      └ <click.core.Context object at 0x7f674def8208>
           │               └ <click.core.Context object at 0x7f674def8208>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7f675e70ba60>
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │          │                └ <click.core.Context object at 0x7f674def8208>
           │          └ <click.core.Command object at 0x7f674e173278>
           └ <click.core.Context object at 0x7f674def8208>
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
           │         │       └ {'data_bundle_path': '/root/.rqalpha', 'locale': 'zh_Hans_CN'}
           │         └ ()
           └ <function update_bundle at 0x7f674e17fd08>
  File "/usr/local/lib/python3.6/site-packages/rqalpha/__main__.py", line 81, in update_bundle
    main.update_bundle(data_bundle_path, locale)
    │                  │                 └ 'zh_Hans_CN'
    │                  └ '/root/.rqalpha'
    └ <module 'rqalpha.main' from '/usr/local/lib/python3.6/site-packages/rqalpha/main.py'>
  File "/usr/local/lib/python3.6/site-packages/rqalpha/main.py", line 128, in update_bundle
    set_locale(locale)
    │          └ 'zh_Hans_CN'
    └ <function set_locale at 0x7f674e17f730>
  File "/usr/local/lib/python3.6/site-packages/rqalpha/utils/config.py", line 129, in set_locale
    locale.setlocale(locale.LC_ALL, "en_US.UTF-8")
    │                └ <module 'locale' from '/usr/local/lib/python3.6/locale.py'>
    └ <module 'locale' from '/usr/local/lib/python3.6/locale.py'>
  File "/usr/local/lib/python3.6/locale.py", line 598, in setlocale
    return _setlocale(category, locale)
           │          │         └ 'en_US.UTF-8'
           │          └ 6
           └ <built-in function setlocale>
locale.Error: unsupported locale setting
The command '/bin/sh -c rqalpha update_bundle' returned a non-zero code: 1

**Comment by xieyuheng** [comment]
https://github.com/ricequant/rqalpha/blob/master/rqalpha/utils/config.py#L127

@wh1100717 
L127, L128 这两行代码是干嘛的?
为什么要改用户的 locale

**Comment by kent119** [comment]
我刚才也遇到了一样的问题。

**Comment by kent119** [comment]
已解决（暂时没发现新的问题）

因为我当前系统的`locale`是`C.UTF-8`，所以我就把`/usr/local/lib/python3.6/site-packages/rqalpha/utils/config.py` 第 129 和 130 行都注释掉，就可以正常更新 bundle，在 notebook 里也可以正常使用策略了。

**Comment by xieyuheng** [comment]
多谢啦
