### ISSUE TITLE
Windows Python 2.7 版本  RQ版本 3.0.6 版本使用#获取所有股票信息出错

### ISSUE THREAD

**Issue by seawav** [ricequant/rqalpha#216]
Windows Python 2.7 版本 
RQ版本 3.0.6 版本使用#获取所有股票信息出错
```python
def getAllStocks():
    stocks = []
    stocks = all_instruments('CS',datetime.date.today()  )

    return stocks
 ```

## 5. 您出现的错误堆栈日志信息

```python_traceback
C:\Windows\system32>rqalpha run -f "C:\Stock\WorkShop\tech-reseach\branches\rqalpha\examples\all_stock_overview.py" -d "C:\Users\kim\.rqalpha\bundle" -s 2017-11-1 -e 2017-11-9 --account stock 100000 --benchmark 002538.XSHE
2017-11-01 INFO init
Error in sys.excepthook:
Traceback (most recent call last):
  File "C:\Python27-13\lib\site-packages\better_exceptions\__init__.py", line 343, in excepthook
    formatted = format_exception(exc, value, tb)
  File "C:\Python27-13\lib\site-packages\rqalpha\utils\logger.py", line 35, in format_exception
    formatted, colored_source = better_exceptions.format_traceback(tb)
  File "C:\Python27-13\lib\site-packages\better_exceptions\__init__.py", line 307, in format_traceback
    formatted, colored = format_traceback_frame(tb)
  File "C:\Python27-13\lib\site-packages\better_exceptions\__init__.py", line 267, in format_traceback_frame
    filename, lineno, function, source, color_source, relevant_values = get_traceback_information(tb)
  File "C:\Python27-13\lib\site-packages\better_exceptions\__init__.py", line 260, in get_traceback_information
    relevant_values = get_relevant_values(source, tb.tb_frame, tree)
  File "C:\Python27-13\lib\site-packages\better_exceptions\__init__.py", line 169, in get_relevant_values
    values.append((text, col, format_value(val)))
  File "C:\Python27-13\lib\site-packages\better_exceptions\__init__.py", line 154, in format_value
    v = repr(v)
  File "C:\Python27-13\lib\site-packages\rqalpha\utils\__init__.py", line 58, in __repr__
    return pprint.pformat(self.__dict__)
  File "C:\Python27-13\lib\pprint.py", line 63, in pformat
    return PrettyPrinter(indent=indent, width=width, depth=depth).pformat(object)
  File "C:\Python27-13\lib\pprint.py", line 122, in pformat
    self._format(object, sio, 0, 0, {}, 0)
  File "C:\Python27-13\lib\pprint.py", line 140, in _format
    rep = self._repr(object, context, level - 1)
  File "C:\Python27-13\lib\pprint.py", line 226, in _repr
    self._depth, level)
  File "C:\Python27-13\lib\pprint.py", line 238, in format
    return _safe_repr(object, context, maxlevels, level)
  File "C:\Python27-13\lib\pprint.py", line 282, in _safe_repr
    vrepr, vreadable, vrecur = saferepr(v, context, maxlevels, level)
  File "C:\Python27-13\lib\pprint.py", line 323, in _safe_repr
    rep = repr(object)
  File "C:\Python27-13\lib\site-packages\rqalpha\utils\__init__.py", line 58, in __repr__
    return pprint.pformat(self.__dict__)
  File "C:\Python27-13\lib\pprint.py", line 63, in pformat
    return PrettyPrinter(indent=indent, width=width, depth=depth).pformat(object)
  File "C:\Python27-13\lib\pprint.py", line 122, in pformat
    self._format(object, sio, 0, 0, {}, 0)
  File "C:\Python27-13\lib\pprint.py", line 140, in _format
    rep = self._repr(object, context, level - 1)
  File "C:\Python27-13\lib\pprint.py", line 226, in _repr
    self._depth, level)
  File "C:\Python27-13\lib\pprint.py", line 238, in format
    return _safe_repr(object, context, maxlevels, level)
  File "C:\Python27-13\lib\pprint.py", line 282, in _safe_repr
    vrepr, vreadable, vrecur = saferepr(v, context, maxlevels, level)
  File "C:\Python27-13\lib\pprint.py", line 323, in _safe_repr
    rep = repr(object)
  File "C:\Python27-13\lib\site-packages\pandas\core\base.py", line 72, in __repr__
    return str(self)
  File "C:\Python27-13\lib\site-packages\pandas\core\base.py", line 52, in __str__
    return self.__bytes__()
  File "C:\Python27-13\lib\site-packages\pandas\core\base.py", line 64, in __bytes__
    return self.__unicode__().encode(encoding, 'replace')
  File "C:\Python27-13\lib\site-packages\pandas\core\indexes\base.py", line 804, in __unicode__
    data = self._format_data()
  File "C:\Python27-13\lib\site-packages\pandas\core\indexes\base.py", line 907, in _format_data
    max_len = max(best_len(head), best_len(tail))
  File "C:\Python27-13\lib\site-packages\pandas\core\indexes\base.py", line 876, in best_len
    return max([adj.len(x) for x in values])
  File "C:\Python27-13\lib\site-packages\pandas\io\formats\format.py", line 288, in len
    return compat.strlen(text, encoding=self.encoding)
  File "C:\Python27-13\lib\site-packages\pandas\compat\__init__.py", line 284, in strlen
    data = data.decode(encoding)
LookupError: unknown encoding: cp65001

Original exception was:
Traceback (most recent call last):
  File "C:\Python27-13\Scripts\rqalpha-script.py", line 11, in <module>
    load_entry_point('rqalpha==3.0.6', 'console_scripts', 'rqalpha')()
  File "C:\Python27-13\lib\site-packages\rqalpha\__main__.py", line 70, in entry_point
    cli(obj={})
  File "C:\Python27-13\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python27-13\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Python27-13\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Python27-13\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python27-13\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\Python27-13\lib\site-packages\rqalpha\__main__.py", line 124, in run
    results = main.run(cfg, source_code=source_code)
  File "C:\Python27-13\lib\site-packages\rqalpha\main.py", line 300, in run
    code = _exception_handler(e)
  File "C:\Python27-13\lib\site-packages\rqalpha\main.py", line 318, in _exception_handler
    better_exceptions.excepthook(e.error.exc_type, e.error.exc_val, e.error.exc_tb)
  File "C:\Python27-13\lib\site-packages\better_exceptions\__init__.py", line 343, in excepthook
    formatted = format_exception(exc, value, tb)
  File "C:\Python27-13\lib\site-packages\rqalpha\utils\logger.py", line 35, in format_exception
    formatted, colored_source = better_exceptions.format_traceback(tb)
  File "C:\Python27-13\lib\site-packages\better_exceptions\__init__.py", line 307, in format_traceback
    formatted, colored = format_traceback_frame(tb)
  File "C:\Python27-13\lib\site-packages\better_exceptions\__init__.py", line 267, in format_traceback_frame
    filename, lineno, function, source, color_source, relevant_values = get_traceback_information(tb)
  File "C:\Python27-13\lib\site-packages\better_exceptions\__init__.py", line 260, in get_traceback_information
    relevant_values = get_relevant_values(source, tb.tb_frame, tree)
  File "C:\Python27-13\lib\site-packages\better_exceptions\__init__.py", line 169, in get_relevant_values
    values.append((text, col, format_value(val)))
  File "C:\Python27-13\lib\site-packages\better_exceptions\__init__.py", line 154, in format_value
    v = repr(v)
  File "C:\Python27-13\lib\site-packages\pandas\core\base.py", line 72, in __repr__
    return str(self)
  File "C:\Python27-13\lib\site-packages\pandas\core\base.py", line 52, in __str__
    return self.__bytes__()
  File "C:\Python27-13\lib\site-packages\pandas\core\base.py", line 64, in __bytes__
    return self.__unicode__().encode(encoding, 'replace')
  File "C:\Python27-13\lib\site-packages\pandas\core\frame.py", line 586, in __unicode__
    line_width=width, show_dimensions=show_dimensions)
  File "C:\Python27-13\lib\site-packages\pandas\core\frame.py", line 1529, in to_string
    formatter.to_string()
  File "C:\Python27-13\lib\site-packages\pandas\io\formats\format.py", line 584, in to_string
    strcols = self._to_str_columns()
  File "C:\Python27-13\lib\site-packages\pandas\io\formats\format.py", line 495, in _to_str_columns
    str_index = self._get_formatted_index(frame)
  File "C:\Python27-13\lib\site-packages\pandas\io\formats\format.py", line 794, in _get_formatted_index
    fmt_index = [index.format(name=show_index_names, formatter=fmt)]
  File "C:\Python27-13\lib\site-packages\pandas\core\indexes\base.py", line 1897, in format
    return self._format_with_header(header, **kwargs)
  File "C:\Python27-13\lib\site-packages\pandas\core\indexes\base.py", line 1921, in _format_with_header
    result = _trim_front(format_array(values, None, justify='left'))
  File "C:\Python27-13\lib\site-packages\pandas\io\formats\format.py", line 1761, in format_array
    return fmt_obj.get_result()
  File "C:\Python27-13\lib\site-packages\pandas\io\formats\format.py", line 1782, in get_result
    return _make_fixed_width(fmt_values, self.justify)
  File "C:\Python27-13\lib\site-packages\pandas\io\formats\format.py", line 2235, in _make_fixed_width
    max_len = np.max([adj.len(x) for x in strings])
  File "C:\Python27-13\lib\site-packages\pandas\io\formats\format.py", line 288, in len
    return compat.strlen(text, encoding=self.encoding)
  File "C:\Python27-13\lib\site-packages\pandas\compat\__init__.py", line 284, in strlen
    data = data.decode(encoding)
LookupError: unknown encoding: cp65001

```
但是调用其他函数正常

**Comment by hzliu** [comment]
这个看起来是你的终端不支持unicode，可以看一下 https://stackoverflow.com/questions/35176270/python-2-7-lookuperror-unknown-encoding-cp65001

all_instruments 的问题应该已经修复
