### ISSUE TITLE
使用--plot参数出现错误提示，无法完成画图的问题

### ISSUE THREAD

**Issue by aw10279** [ricequant/rqalpha#218]
rqalpha:3.08
python:3.5
OS:win7
问题：用不同方式测试几个策略时发现只要带--plot参数，就会出现“OverflowError: Python int too large to convert to C long”和“Exception in Tkinter callback”错误提示，重装matplotlib2.10问题依然存在。
错误日志：
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\python3.5\lib\tkinter\__init__.py", line 1549, in __call__
    return self.func(*args)
  File "D:\python3.5\lib\tkinter\__init__.py", line 596, in callit
    func(*args)
  File "D:\python3.5\lib\site-packages\matplotlib\backends\backend_tkagg.py", line 323, in idle_draw
    self.draw()
  File "D:\python3.5\lib\site-packages\matplotlib\backends\backend_tkagg.py", line 304, in draw
    FigureCanvasAgg.draw(self)
  File "D:\python3.5\lib\site-packages\matplotlib\backends\backend_agg.py", line 430, in draw
    self.figure.draw(self.renderer)
  File "D:\python3.5\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "D:\python3.5\lib\site-packages\matplotlib\figure.py", line 1295, in draw
    renderer, self, artists, self.suppressComposite)
  File "D:\python3.5\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "D:\python3.5\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "D:\python3.5\lib\site-packages\matplotlib\axes\_base.py", line 2397, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "D:\python3.5\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "D:\python3.5\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "D:\python3.5\lib\site-packages\matplotlib\axis.py", line 1133, in draw
    ticks_to_draw = self._update_ticks(renderer)
  File "D:\python3.5\lib\site-packages\matplotlib\axis.py", line 974, in _update_ticks
    tick_tups = list(self.iter_ticks())
  File "D:\python3.5\lib\site-packages\matplotlib\axis.py", line 917, in iter_ticks
    majorLocs = self.major.locator()
  File "D:\python3.5\lib\site-packages\matplotlib\dates.py", line 1061, in __call__
    self.refresh()
  File "D:\python3.5\lib\site-packages\matplotlib\dates.py", line 1081, in refresh
    dmin, dmax = self.viewlim_to_dt()
  File "D:\python3.5\lib\site-packages\matplotlib\dates.py", line 839, in viewlim_to_dt
    return num2date(vmin, self.tz), num2date(vmax, self.tz)
  File "D:\python3.5\lib\site-packages\matplotlib\dates.py", line 445, in num2date
    return _from_ordinalf(x, tz)
  File "D:\python3.5\lib\site-packages\matplotlib\dates.py", line 260, in _from_ordinalf
    dt = datetime.datetime.fromordinal(ix).replace(tzinfo=UTC)
OverflowError: Python int too large to convert to C long

Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\python3.5\lib\tkinter\__init__.py", line 1549, in __call__
    return self.func(*args)
  File "D:\python3.5\lib\site-packages\matplotlib\backends\backend_tkagg.py", line 233, in resize
    self.show()
  File "D:\python3.5\lib\site-packages\matplotlib\backends\backend_tkagg.py", line 304, in draw
    FigureCanvasAgg.draw(self)
  File "D:\python3.5\lib\site-packages\matplotlib\backends\backend_agg.py", line 430, in draw
    self.figure.draw(self.renderer)
  File "D:\python3.5\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "D:\python3.5\lib\site-packages\matplotlib\figure.py", line 1295, in draw
    renderer, self, artists, self.suppressComposite)
  File "D:\python3.5\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "D:\python3.5\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "D:\python3.5\lib\site-packages\matplotlib\axes\_base.py", line 2397, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "D:\python3.5\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "D:\python3.5\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "D:\python3.5\lib\site-packages\matplotlib\axis.py", line 1133, in draw
    ticks_to_draw = self._update_ticks(renderer)
  File "D:\python3.5\lib\site-packages\matplotlib\axis.py", line 974, in _update_ticks
    tick_tups = list(self.iter_ticks())
  File "D:\python3.5\lib\site-packages\matplotlib\axis.py", line 917, in iter_ticks
    majorLocs = self.major.locator()
  File "D:\python3.5\lib\site-packages\matplotlib\dates.py", line 1061, in __call__
    self.refresh()
  File "D:\python3.5\lib\site-packages\matplotlib\dates.py", line 1081, in refresh
    dmin, dmax = self.viewlim_to_dt()
  File "D:\python3.5\lib\site-packages\matplotlib\dates.py", line 839, in viewlim_to_dt
    return num2date(vmin, self.tz), num2date(vmax, self.tz)
  File "D:\python3.5\lib\site-packages\matplotlib\dates.py", line 445, in num2date
    return _from_ordinalf(x, tz)
  File "D:\python3.5\lib\site-packages\matplotlib\dates.py", line 260, in _from_ordinalf
    dt = datetime.datetime.fromordinal(ix).replace(tzinfo=UTC)
OverflowError: Python int too large to convert to C long

**Comment by cedricporter** [comment]
因为 pandas 0.21.0 不太兼容 matplotlib 。您现在更可以更新 RQAlpha  到 3.0.9 ，会限制 pandas 版本在我们测试过的范围内。

**Comment by aw10279** [comment]
RQAlpha更新到3.0.9同时pandas回到0.20，问题不再出现。非常感谢！！
