### ISSUE TITLE
matplotlib的date格式出现问题Python int too large to convert to C long

### ISSUE THREAD

**Issue by liupingchao** [ricequant/rqalpha#221]
## 1. RQAlpha的版本
(3.0.6)
## 2. Python的版本
3.5，matplotlib版本2.1.0
## 3. 是Windows/Linux/MacOS or others?
win 10
## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
运行的是示例的buy_and_hold.py,这个问题应该和策略代码无关，是一个格式的问题。
## 5. 您出现的错误堆栈日志信息
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\envs\rqalpha\lib\tkinter\__init__.py", line 1558, in __call__
    return self.func(*args)
  File "C:\Program Files\Anaconda3\envs\rqalpha\lib\tkinter\__init__.py", line 605, in callit
    func(*args)
  File "C:\Program Files\Anaconda3\envs\rqalpha\lib\site-packages\matplotlib\backends\backend_tkagg.py", line 323, in idle_draw
    self.draw()
  File "C:\Program Files\Anaconda3\envs\rqalpha\lib\site-packages\matplotlib\backends\backend_tkagg.py", line 304, in draw
    FigureCanvasAgg.draw(self)
  File "C:\Program Files\Anaconda3\envs\rqalpha\lib\site-packages\matplotlib\backends\backend_agg.py", line 430, in draw
    self.figure.draw(self.renderer)
  File "C:\Program Files\Anaconda3\envs\rqalpha\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Program Files\Anaconda3\envs\rqalpha\lib\site-packages\matplotlib\figure.py", line 1295, in draw
    renderer, self, artists, self.suppressComposite)
  File "C:\Program Files\Anaconda3\envs\rqalpha\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\Program Files\Anaconda3\envs\rqalpha\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Program Files\Anaconda3\envs\rqalpha\lib\site-packages\matplotlib\axes\_base.py", line 2399, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "C:\Program Files\Anaconda3\envs\rqalpha\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\Program Files\Anaconda3\envs\rqalpha\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Program Files\Anaconda3\envs\rqalpha\lib\site-packages\matplotlib\axis.py", line 1133, in draw
    ticks_to_draw = self._update_ticks(renderer)
  File "C:\Program Files\Anaconda3\envs\rqalpha\lib\site-packages\matplotlib\axis.py", line 974, in _update_ticks
    tick_tups = list(self.iter_ticks())
  File "C:\Program Files\Anaconda3\envs\rqalpha\lib\site-packages\matplotlib\axis.py", line 917, in iter_ticks
    majorLocs = self.major.locator()
  File "C:\Program Files\Anaconda3\envs\rqalpha\lib\site-packages\matplotlib\dates.py", line 1054, in __call__
    self.refresh()
  File "C:\Program Files\Anaconda3\envs\rqalpha\lib\site-packages\matplotlib\dates.py", line 1074, in refresh
    dmin, dmax = self.viewlim_to_dt()
  File "C:\Program Files\Anaconda3\envs\rqalpha\lib\site-packages\matplotlib\dates.py", line 832, in viewlim_to_dt
    return num2date(vmin, self.tz), num2date(vmax, self.tz)
  File "C:\Program Files\Anaconda3\envs\rqalpha\lib\site-packages\matplotlib\dates.py", line 441, in num2date
    return _from_ordinalf(x, tz)
  File "C:\Program Files\Anaconda3\envs\rqalpha\lib\site-packages\matplotlib\dates.py", line 256, in _from_ordinalf
    dt = datetime.datetime.fromordinal(ix).replace(tzinfo=UTC)
OverflowError: Python int too large to convert to C long
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\envs\rqalpha\lib\tkinter\__init__.py", line 1558, in __call__
    return self.func(*args)
  File "C:\Program Files\Anaconda3\envs\rqalpha\lib\site-packages\matplotlib\backends\backend_tkagg.py", line 233, in resize
    self.show()
  File "C:\Program Files\Anaconda3\envs\rqalpha\lib\site-packages\matplotlib\backends\backend_tkagg.py", line 304, in draw
    FigureCanvasAgg.draw(self)
  File "C:\Program Files\Anaconda3\envs\rqalpha\lib\site-packages\matplotlib\backends\backend_agg.py", line 430, in draw
    self.figure.draw(self.renderer)
  File "C:\Program Files\Anaconda3\envs\rqalpha\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Program Files\Anaconda3\envs\rqalpha\lib\site-packages\matplotlib\figure.py", line 1295, in draw
    renderer, self, artists, self.suppressComposite)
  File "C:\Program Files\Anaconda3\envs\rqalpha\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\Program Files\Anaconda3\envs\rqalpha\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Program Files\Anaconda3\envs\rqalpha\lib\site-packages\matplotlib\axes\_base.py", line 2399, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "C:\Program Files\Anaconda3\envs\rqalpha\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\Program Files\Anaconda3\envs\rqalpha\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\Program Files\Anaconda3\envs\rqalpha\lib\site-packages\matplotlib\axis.py", line 1133, in draw
    ticks_to_draw = self._update_ticks(renderer)
  File "C:\Program Files\Anaconda3\envs\rqalpha\lib\site-packages\matplotlib\axis.py", line 974, in _update_ticks
    tick_tups = list(self.iter_ticks())
  File "C:\Program Files\Anaconda3\envs\rqalpha\lib\site-packages\matplotlib\axis.py", line 917, in iter_ticks
    majorLocs = self.major.locator()
  File "C:\Program Files\Anaconda3\envs\rqalpha\lib\site-packages\matplotlib\dates.py", line 1054, in __call__
    self.refresh()
  File "C:\Program Files\Anaconda3\envs\rqalpha\lib\site-packages\matplotlib\dates.py", line 1074, in refresh
    dmin, dmax = self.viewlim_to_dt()
  File "C:\Program Files\Anaconda3\envs\rqalpha\lib\site-packages\matplotlib\dates.py", line 832, in viewlim_to_dt
    return num2date(vmin, self.tz), num2date(vmax, self.tz)
  File "C:\Program Files\Anaconda3\envs\rqalpha\lib\site-packages\matplotlib\dates.py", line 441, in num2date
    return _from_ordinalf(x, tz)
  File "C:\Program Files\Anaconda3\envs\rqalpha\lib\site-packages\matplotlib\dates.py", line 256, in _from_ordinalf
    dt = datetime.datetime.fromordinal(ix).replace(tzinfo=UTC)
OverflowError: Python int too large to convert to C long

**Comment by cedricporter** [comment]
pandas 0.21.0 不太兼容 matplotlib 。您现在更可以更新 RQAlpha 到 3.0.9 ，会限制 pandas 版本在我们测试过的范围内。
