### ISSUE TITLE
如果要进行分钟线，请注意是否拥有对应的数据源?

### ISSUE THREAD

**Issue by yssource** [ricequant/rqalpha#227]
[如果要进行分钟线，请注意是否拥有对应的数据源](https://github.com/ricequant/rqalpha/blob/6d1887fbc418c295373417bea1b9ffe9b5c7a5da/rqalpha/config.yml#L23)

[raise NotImplementedError](https://github.com/ricequant/rqalpha/blob/develop/rqalpha/data/base_data_source.py#L121-L123)

既然, 通过第三方数据源是可以配置 frequency=1m 的, 为啥这里还 `raise NotImplementedError`, 导致事实上不能跑 1m

```
Traceback (most recent call last):
  File "/home/devel/rqalpha/rqalpha/model/bar.py", line 339, in __getitem__
    return self._cache[order_book_id]
KeyError: '399006.XSHE'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/devel/rqalpha/rqalpha/model/bar.py", line 342, in __getitem__
    bar = self._data_proxy.get_bar(order_book_id, self._dt, self._frequency)
  File "/home/devel/rqalpha/rqalpha/data/data_proxy.py", line 133, in get_bar
    bar = self._data_source.get_bar(instrument, dt, frequency)
  File "/home/devel/rqalpha-mod-tushare/rqalpha_mod_tushare/data_source.py", line 46, in get_bar
    return super(TushareKDataSource, self).get_bar(instrument, dt, frequency)
  File "/home/devel/rqalpha/rqalpha/data/base_data_source.py", line 123, in get_bar
    raise NotImplementedError
NotImplementedError

```

**Comment by yssource** [comment]
rqalpha 的逻辑是对的. 第三方 mod 应该 override, get_bar history_bars 这两个方法.
我是用的第三方 mod 做 '1m'
 [if frequency != '1d':](https://github.com/ricequant/rqalpha-mod-tushare/blob/master/rqalpha_mod_tushare/data_source.py#L43)
[if frequency != '1d' or not skip_suspended:](https://github.com/ricequant/rqalpha-mod-tushare/blob/master/rqalpha_mod_tushare/data_source.py#L55)

个人觉得是 他那边错了. 应该是 `if frequency == '1d'`, 而非 `if frequency != '1d'`
