### ISSUE TITLE
安裝錯誤

### ISSUE THREAD

**Issue by morris9795** [ricequant/rqalpha#229]
Python的版本 : 3.5 
windows
依照安裝步驟操作
順利安裝完 bcolz之後
安裝rqalpha發生錯誤
Running setup.py bdist_wheel for logbook ... error
  Failed building wheel for logbook
  Running setup.py clean for logbook
  Failed cleaning build dir for logbook
  Running setup.py bdist_wheel for jsonpickle ... done
  Stored in directory: C:\Users\morris9795\AppData\Local\pip\Cache\wheels\03\10\4e\05c2614c6d900670e0d035c702eb197641e19c8e63b
2fff364
  Running setup.py bdist_wheel for dill ... done
  Stored in directory: C:\Users\morris9795\AppData\Local\pip\Cache\wheels\5a\33\46\2a9339e6a1f411fd6597c52628e7a5bb173247578d9
a350912
  Running setup.py bdist_wheel for line-profiler ... error
  Failed building wheel for line-profiler

Exception:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa5 in position 3: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa5 in position 3: invalid start byte

請問這是甚麼樣的錯誤導致安裝失敗呢 謝謝

**Comment by morris9795** [comment]
後續補充:
我已經自行成功安裝完 line-profiler 2.1.1 & logbook1.1.0
不過安裝rqalpha的過程仍有報錯

Building wheels for collected packages: logbook
  Running setup.py bdist_wheel for logbook ... error
  Failed building wheel for logbook
  Running setup.py clean for logbook
  Failed cleaning build dir for logbook
Failed to build logbook
Installing collected packages: jsonpickle, logbook, pyreadline, dill, better-exceptions, simplejson, tabulate, rqalpha
  Found existing installation: Logbook 1.1.0
    Uninstalling Logbook-1.1.0:
      Successfully uninstalled Logbook-1.1.0
  Running setup.py install for logbook ... error
  Rolling back uninstall of Logbook
Exception:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa5 in position 3: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa5 in position 3: invalid start byte

請問這是什麼樣的錯誤?

**Comment by wuxin1030** [comment]
我也遇到这个问题了。一模一样。

**Comment by zsluedem** [comment]
安装路径不能有中文

**Comment by morris9795** [comment]
將安裝環境正確指向虛擬環境之後就解決了 wuxin1030可以試試看

**Comment by sharpwang** [comment]
打开c:\program files\python36\lib\site-packages\pip\compat\__init__.py约75行
return s.decode('utf_8') 改为return s.decode('cp936')

**Comment by ErwinLu** [comment]
morris9795你好，请问 将安装环境正确指向虚拟环境 是什么意思？该怎么做？

**Comment by ErwinLu** [comment]
@wuxin1030 请问你的问题解决了吗？

**Comment by t985026** [comment]
我也有一樣的問題，但我使用
conda install -c anaconda line_profiler
方式安裝完成了，Python 3.6.4 & conda 4.4.10

**Comment by ErwinLu** [comment]
感谢你的提醒！
