### ISSUE TITLE
环境为：win10，anaconda2，python2.7， rqalpha3.0.9

### ISSUE THREAD

**Issue by Zhangjiahong001** [ricequant/rqalpha#231]
(C:\Users\82193\Anaconda2) C:\Users\82193>rqalpha update_bundle
灏濊瘯 http://7xjci3.com1.z0.glb.clouddn.com/bundles_v3/rqbundle_20171230.tar.bz2 ...
灏濊瘯 http://7xjci3.com1.z0.glb.clouddn.com/bundles_v3/rqbundle_20171229.tar.bz2 ...
涓嬭浇涓?...  [------------------------------------]    0%Traceback (most recent call last):
  File "c:\users\82193\anaconda2\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\users\82193\anaconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
         \u2502       \u2514 {'__builtins__': <module '__builtin__' (built-in)>, '__file__': 'C:\Users\82193\Anaconda2\Scripts\rqalpha.exe\__main__.py'...
qalpha.exe\__main__.py", line 2>dule> at 0000000005634BB0, file "C:\Users\82193\Anaconda2\Scripts
  File "C:\Users\82193\Anaconda2\Scripts\rqalpha.exe\__main__.py", line 9, in <module>
    sys.exit(entry_point())
    \u2502        \u2514 <function entry_point at 0x0000000009BF9438>
    \u2514 <module 'sys' (built-in)>
  File "c:\users\82193\anaconda2\lib\site-packages\rqalpha\__main__.py", line 70, in entry_point
    cli(obj={})
    \u2514 <click.core.Group object at 0x0000000009BF6320>
  File "c:\users\82193\anaconda2\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
           \u2502          \u2502       \u2514 {'obj': {'VERBOSE': 0}}
           \u2502          \u2514 ()
           \u2514 <click.core.Group object at 0x0000000009BF6320>
  File "c:\users\82193\anaconda2\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
         \u2502           \u2514 <click.core.Context object at 0x0000000009C83B70>
         \u2514 <click.core.Group object at 0x0000000009BF6320>
  File "c:\users\82193\anaconda2\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           \u2502               \u2502                      \u2514 <click.core.Context object at 0x0000000009C9CFD0>
           \u2502               \u2514 <click.core.Context object at 0x0000000009C9CFD0>
           \u2514 <function _process_result at 0x0000000009CA6198>
  File "c:\users\82193\anaconda2\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           \u2502          \u2502                \u2514 <click.core.Context object at 0x0000000009C9CFD0>
           \u2502          \u2514 <click.core.Command object at 0x0000000009BF64E0>
           \u2514 <click.core.Context object at 0x0000000009C9CFD0>
  File "c:\users\82193\anaconda2\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
           \u2502         \u2502       \u2514 {'locale': u'zh_Hans_CN', 'data_bundle_path': 'C:\Users\82193/.rqalpha'}
           \u2502         \u2514 ()
           \u2514 <function update_bundle at 0x0000000009BF97B8>
  File "c:\users\82193\anaconda2\lib\site-packages\rqalpha\__main__.py", line 81, in update_bundle
    main.update_bundle(data_bundle_path, locale)
    \u2502                  \u2502                 \u2514 u'zh_Hans_CN'
    \u2502                  \u2514 'C:\Users\82193/.rqalpha'
qalpha\main.pyc'>e 'rqalpha.main' from 'c:\users\82193naconda2\lib\site-packages
  File "c:\users\82193\anaconda2\lib\site-packages\rqalpha\main.py", line 161, in update_bundle
    with click.progressbar(length=total_length, label=_(u"downloading ...")) as bar:
  File "c:\users\82193\anaconda2\lib\site-packages\click\_termui_impl.py", line 94, in __enter__
    self.render_progress()
    \u2514 <click._termui_impl.ProgressBar object at 0x000000000AD57A20>
  File "c:\users\82193\anaconda2\lib\site-packages\click\_termui_impl.py", line 230, in render_progress
    echo(line, file=self.file, color=self.color, nl=nl)
    \u2502    \u2502          \u2502                \u2502              \u2514 False
    \u2502    \u2502          \u2502                \u2514 <click._termui_impl.ProgressBar object at 0x000000000AD57A20>
    \u2502    \u2502          \u2514 <click._termui_impl.ProgressBar object at 0x000000000AD57A20>
涓嬭浇涓?...  [------------------------------------]    0%'Error in sys.excepthook:
Traceback (most recent call last):
  File "c:\users\82193\anaconda2\lib\site-packages\better_exceptions\__init__.py", line 344, in excepthook
    write_stream(formatted)
  File "c:\users\82193\anaconda2\lib\site-packages\better_exceptions\__init__.py", line 327, in write_stream
    STREAM.write(data)
  File "c:\users\82193\anaconda2\lib\site-packages\colorama\ansitowin32.py", line 36, in write
    self.__convertor.write(text)
  File "c:\users\82193\anaconda2\lib\site-packages\colorama\ansitowin32.py", line 137, in write
    self.write_and_convert(text)
  File "c:\users\82193\anaconda2\lib\site-packages\colorama\ansitowin32.py", line 162, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "c:\users\82193\anaconda2\lib\site-packages\colorama\ansitowin32.py", line 170, in write_plain_text
    self.wrapped.write(text[start:end])
IOError: [Errno 0] Error

Original exception was:
Traceback (most recent call last):
  File "c:\users\82193\anaconda2\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\users\82193\anaconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\82193\Anaconda2\Scripts\rqalpha.exe\__main__.py", line 9, in <module>
  File "c:\users\82193\anaconda2\lib\site-packages\rqalpha\__main__.py", line 70, in entry_point
    cli(obj={})
  File "c:\users\82193\anaconda2\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\82193\anaconda2\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\82193\anaconda2\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\82193\anaconda2\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\82193\anaconda2\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\82193\anaconda2\lib\site-packages\rqalpha\__main__.py", line 81, in update_bundle
    main.update_bundle(data_bundle_path, locale)
  File "c:\users\82193\anaconda2\lib\site-packages\rqalpha\main.py", line 161, in update_bundle
    with click.progressbar(length=total_length, label=_(u"downloading ...")) as bar:
  File "c:\users\82193\anaconda2\lib\site-packages\click\_termui_impl.py", line 94, in __enter__
    self.render_progress()
  File "c:\users\82193\anaconda2\lib\site-packages\click\_termui_impl.py", line 230, in render_progress
    echo(line, file=self.file, color=self.color, nl=nl)
  File "c:\users\82193\anaconda2\lib\site-packages\click\utils.py", line 259, in echo
    file.write(message)
  File "c:\users\82193\anaconda2\lib\site-packages\click\_compat.py", line 577, in _safe_write
    return _write(s)
  File "c:\users\82193\anaconda2\lib\site-packages\colorama\ansitowin32.py", line 36, in write
    self.__convertor.write(text)
  File "c:\users\82193\anaconda2\lib\site-packages\colorama\ansitowin32.py", line 137, in write
    self.write_and_convert(text)
  File "c:\users\82193\anaconda2\lib\site-packages\colorama\ansitowin32.py", line 165, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "c:\users\82193\anaconda2\lib\site-packages\colorama\ansitowin32.py", line 170, in write_plain_text
    self.wrapped.write(text[start:end])
  File "c:\users\82193\anaconda2\lib\site-packages\click\_winconsole.py", line 185, in write
    return self.buffer.write(x)
  File "c:\users\82193\anaconda2\lib\site-packages\colorama\ansitowin32.py", line 36, in write
    self.__convertor.write(text)
  File "c:\users\82193\anaconda2\lib\site-packages\colorama\ansitowin32.py", line 137, in write
    self.write_and_convert(text)
  File "c:\users\82193\anaconda2\lib\site-packages\colorama\ansitowin32.py", line 165, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "c:\users\82193\anaconda2\lib\site-packages\colorama\ansitowin32.py", line 170, in write_plain_text
    self.wrapped.write(text[start:end])
  File "c:\users\82193\anaconda2\lib\site-packages\colorama\ansitowin32.py", line 36, in write
    self.__convertor.write(text)
  File "c:\users\82193\anaconda2\lib\site-packages\colorama\ansitowin32.py", line 137, in write
    self.write_and_convert(text)
  File "c:\users\82193\anaconda2\lib\site-packages\colorama\ansitowin32.py", line 165, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "c:\users\82193\anaconda2\lib\site-packages\colorama\ansitowin32.py", line 170, in write_plain_text
    self.wrapped.write(text[start:end])
  File "c:\users\82193\anaconda2\lib\site-packages\colorama\ansitowin32.py", line 36, in write
    self.__convertor.write(text)
  File "c:\users\82193\anaconda2\lib\site-packages\colorama\ansitowin32.py", line 137, in write
    self.write_and_convert(text)
  File "c:\users\82193\anaconda2\lib\site-packages\colorama\ansitowin32.py", line 165, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "c:\users\82193\anaconda2\lib\site-packages\colorama\ansitowin32.py", line 170, in write_plain_text
    self.wrapped.write(text[start:end])
  File "c:\users\82193\anaconda2\lib\site-packages\colorama\ansitowin32.py", line 36, in write
    self.__convertor.write(text)
  File "c:\users\82193\anaconda2\lib\site-packages\colorama\ansitowin32.py", line 137, in write
    self.write_and_convert(text)
  File "c:\users\82193\anaconda2\lib\site-packages\colorama\ansitowin32.py", line 165, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "c:\users\82193\anaconda2\lib\site-packages\colorama\ansitowin32.py", line 170, in write_plain_text
    self.wrapped.write(text[start:end])
IOError: [Errno 0] Error

**Comment by Zhangjiahong001** [comment]
rqalpha update_bundle数据更新的时候不成功
