### ISSUE TITLE
安装了最新版本，运行例子报错

### ISSUE THREAD

**Issue by lzhw520110** [ricequant/rqalpha#244]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

## 5. 您出现的错误堆栈日志信息

         loaded from files will be inspected!
[2018-01-23 11:20:40.792000] ERROR: system_log: ******************************
[2018-01-23 11:20:40.792000] ERROR: system_log: ******************************
[2018-01-23 11:20:40.792000] ERROR: system_log: Mod Import Error: rqalpha.mod.risk_manager, error: No module named risk_manager
[2018-01-23 11:20:40.789000] DEBUG: basic_system_log: 
{'base': {'accounts': {'STOCK': 100000.0},
          'benchmark': '000300.XSHG',
          'commission_multiplier': 1,
          'data_bundle_path': 'C:\\Users\\Lenovo/.rqalpha\\bundle',
          'end_date': datetime.date(2016, 12, 1),
          'frequency': '1d',
          'future_starting_cash': 0,
          'handle_split': False,
          'init_positions': [],
          'margin_multiplier': 1,
          'matching_type': 'current_bar',
          'persist': False,
          'persist_mode': PERSIST_MODE.REAL_TIME,
          'resume_mode': False,
          'run_id': 9999,
          'run_type': RUN_TYPE.BACKTEST,
          'slippage': 0,
          'source_code': None,
          'start_date': datetime.date(2016, 6, 1),
          'stock_starting_cash': 0,
          'strategy_file': 'strategy.py',
          'strategy_type': 'stock'},
 'extra': {'context_vars': None,
           'dividend_reinvestment': False,
           'enable_profiler': False,
           'force_run_init_when_pt_resume': False,
           'is_hold': False,
           'locale': 'zh_Hans_CN',
           'log_level': 'verbose',
           'logger': [],
           'user_log_disabled': False,
           'user_system_log_disabled': False},
 'mod': {'analyser': {'enabled': True,
                      'lib': 'rqalpha.mod.analyser',
                      'output_file': None,
                      'plot': None,
                      'plot_save_file': None,
                      'priority': 100,
                      'record': True,
                      'report_save_path': None},
         'funcat_api': {'enabled': False,
                        'lib': 'rqalpha.mod.funcat_api',
                        'priority': 200},
         'progress': {'enabled': False,
                      'lib': 'rqalpha.mod.progress',
                      'priority': 400},
         'progressive_output_csv': {'enabled': False,
                                    'lib': 'rqalpha.mod.progressive_output_csv',
                                    'output_path': './',
                                    'priority': 600},
         'risk_manager': {'available_cash': True,
                          'available_position': True,
                          'enabled': True,
                          'lib': 'rqalpha.mod.risk_manager',
                          'priority': 700},
         'simple_stock_realtime_trade': {'enabled': False,
                                         'fps': 3,
                                         'lib': 'rqalpha.mod.simple_stock_realtime_trade',
                                         'persist_path': './persist/strategy/',
                                         'priority': 500},
         'simulation': {'enabled': True,
                        'lib': 'rqalpha.mod.simulation',
                        'priority': 100},
         'sys_accounts': {'enabled': True},
         'sys_analyser': {'enabled': True, 'plot': True},
         'sys_funcat': {'enabled': False},
         'sys_progress': {'enabled': True},
         'sys_risk': {'enabled': True},
         'sys_simulation': {'enabled': True},
         'sys_stock_realtime': {'enabled': False}},
 'validator': {'bar_limit': True,
               'cash_return_by_stock_delisted': False,
               'close_amount': True},
 'version': '0.1.1',
 'whitelist': ['base', 'extra', 'validator', 'mod']}
[2018-01-23 11:20:40.790000] DEBUG: system_log: 载入 Mod rqalpha.mod.risk_manager
[2018-01-23 11:20:40.880000] ERROR: system_log: tear down fail for risk_manager
Traceback (most recent call last):
  File "C:\Users\Lenovo\Anaconda2\lib\site-packages\rqalpha\mod\__init__.py", line 77, in tear_down
    ret = self._mod_dict[mod_name].tear_down(*args)
KeyError: 'risk_manager'
>>> [2018-01-23 11:20:40.879000] ERROR: system_log: tear down fail for analyser
Traceback (most recent call last):
  File "C:\Users\Lenovo\Anaconda2\lib\site-packages\rqalpha\mod\__init__.py", line 77, in tear_down
    ret = self._mod_dict[mod_name].tear_down(*args)
KeyError: 'analyser'
[2018-01-23 11:20:40.880000] DEBUG: basic_system_log: mod tear_down [START] sys_analyser
[2018-01-23 11:20:40.880000] ERROR: system_log: tear down fail for sys_analyser
Traceback (most recent call last):
  File "C:\Users\Lenovo\Anaconda2\lib\site-packages\rqalpha\mod\__init__.py", line 77, in tear_down
    ret = self._mod_dict[mod_name].tear_down(*args)
KeyError: 'sys_analyser'
[2018-01-23 11:20:40.880000] DEBUG: basic_system_log: mod tear_down [START] risk_manager
[2018-01-23 11:20:40.879000] DEBUG: basic_system_log: mod tear_down [START] analyser
[2018-01-23 11:20:40.879000] ERROR: system_log: tear down fail for simulation
Traceback (most recent call last):
  File "C:\Users\Lenovo\Anaconda2\lib\site-packages\rqalpha\mod\__init__.py", line 77, in tear_down
    ret = self._mod_dict[mod_name].tear_down(*args)
KeyError: 'simulation'
[2018-01-23 11:20:40.879000] DEBUG: basic_system_log: mod tear_down [START] simulation
[2018-01-23 11:20:40.878000] ERROR: system_log: tear down fail for sys_accounts
Traceback (most recent call last):
  File "C:\Users\Lenovo\Anaconda2\lib\site-packages\rqalpha\mod\__init__.py", line 77, in tear_down
    ret = self._mod_dict[mod_name].tear_down(*args)
KeyError: 'sys_accounts'
[2018-01-23 11:20:40.878000] DEBUG: basic_system_log: mod tear_down [START] sys_accounts
[2018-01-23 11:20:40.878000] ERROR: system_log: tear down fail for sys_progress
Traceback (most recent call last):
  File "C:\Users\Lenovo\Anaconda2\lib\site-packages\rqalpha\mod\__init__.py", line 77, in tear_down
    ret = self._mod_dict[mod_name].tear_down(*args)
KeyError: 'sys_progress'
[2018-01-23 11:20:40.878000] DEBUG: basic_system_log: mod tear_down [START] sys_progress
[2018-01-23 11:20:40.877000] ERROR: system_log: tear down fail for sys_simulation
Traceback (most recent call last):
  File "C:\Users\Lenovo\Anaconda2\lib\site-packages\rqalpha\mod\__init__.py", line 77, in tear_down
    ret = self._mod_dict[mod_name].tear_down(*args)
KeyError: 'sys_simulation'
[2018-01-23 11:20:40.876000] ERROR: system_log: 策略运行产生异常
Traceback (most recent call last):
  File "C:\Users\Lenovo\Anaconda2\lib\site-packages\rqalpha\main.py", line 197, in run
    mod_handler.set_env(env)
  File "C:\Users\Lenovo\Anaconda2\lib\site-packages\rqalpha\mod\__init__.py", line 51, in set_env
    mod_module = import_mod(lib_name)
  File "C:\Users\Lenovo\Anaconda2\lib\site-packages\rqalpha\utils\package_helper.py", line 23, in import_mod
    return import_module(mod_name)
  File "C:\Users\Lenovo\Anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named risk_manager
[2018-01-23 11:20:40.877000] DEBUG: basic_system_log: mod tear_down [START] sys_risk
[2018-01-23 11:20:40.877000] ERROR: system_log: tear down fail for sys_risk
Traceback (most recent call last):
  File "C:\Users\Lenovo\Anaconda2\lib\site-packages\rqalpha\mod\__init__.py", line 77, in tear_down
    ret = self._mod_dict[mod_name].tear_down(*args)
KeyError: 'sys_risk'
[2018-01-23 11:20:40.877000] DEBUG: basic_system_log: mod tear_down [START] sys_simulation
2018-01-23 ERROR No module named risk_manager
Traceback (most recent call last):
  File "C:\Users\Lenovo\Anaconda2\lib\site-packages\rqalpha\main.py", line 197, in run
    mod_handler.set_env(env)
    ��                   �� <rqalpha.environment.Environment object at 0x000000000DAD6240>
    �� <rqalpha.mod.ModHandler object at 0x000000001069E2E8>
  File "C:\Users\Lenovo\Anaconda2\lib\site-packages\rqalpha\mod\__init__.py", line 51, in set_env
    mod_module = import_mod(lib_name)
                 ��          �� 'rqalpha.mod.risk_manager'
                 �� <function import_mod at 0x000000000EA07C18>
  File "C:\Users\Lenovo\Anaconda2\lib\site-packages\rqalpha\utils\package_helper.py", line 23, in import_mod
    return import_module(mod_name)
           ��             �� 'rqalpha.mod.risk_manager'
           �� <function import_module at 0x000000000CDE0C18>
  File "C:\Users\Lenovo\Anaconda2\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
               �� 'rqalpha.mod.risk_manager'
ImportError: No module named risk_manager

**Comment by hzliu** [comment]
删除用户目录中 config.yml mod_config.yml

2018-01-23 11:21 GMT+08:00 lzhw520110 <notifications@github.com>:
