### ISSUE TITLE
'better_exceptions' has no attribute 'format_traceback'怎么解决

### ISSUE THREAD

**Issue by fairleehu** [ricequant/rqalpha#245]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

## 1. RQAlpha的版本
3.0.9
## 2. Python的版本
3.6.0
## 3. 是Windows/Linux/MacOS or others?
macos
## 5. 您出现的错误堆栈日志信息
File "/Users/huxinghui/virtualenv/aiquant/lib/python3.6/site-packages/rqalpha/main.py", line 201, in run
    env.set_data_source(BaseDataSource(config.base.data_bundle_path))
  File "/Users/huxinghui/virtualenv/aiquant/lib/python3.6/site-packages/rqalpha/data/base_data_source.py", line 44, in __init__
    raise RuntimeError('bundle path {} not exist'.format(os.path.abspath))
RuntimeError: bundle path <function abspath at 0x10172cb70> not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/huxinghui/virtualenv/aiquant/bin/rqalpha", line 11, in <module>
    sys.exit(entry_point())
  File "/Users/huxinghui/virtualenv/aiquant/lib/python3.6/site-packages/rqalpha/__main__.py", line 70, in entry_point
    cli(obj={})
  File "/Users/huxinghui/virtualenv/aiquant/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/huxinghui/virtualenv/aiquant/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/huxinghui/virtualenv/aiquant/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/huxinghui/virtualenv/aiquant/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/huxinghui/virtualenv/aiquant/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/huxinghui/virtualenv/aiquant/lib/python3.6/site-packages/rqalpha/__main__.py", line 126, in run
    results = main.run(cfg, source_code=source_code)
  File "/Users/huxinghui/virtualenv/aiquant/lib/python3.6/site-packages/rqalpha/main.py", line 315, in run
    code = _exception_handler(user_exc)
  File "/Users/huxinghui/virtualenv/aiquant/lib/python3.6/site-packages/rqalpha/main.py", line 326, in _exception_handler
    better_exceptions.excepthook(e.error.exc_type, e.error.exc_val, e.error.exc_tb)
  File "/Users/huxinghui/virtualenv/aiquant/lib/python3.6/site-packages/better_exceptions/__init__.py", line 53, in excepthook
    formatted = format_exception(exc, value, tb)
  File "/Users/huxinghui/virtualenv/aiquant/lib/python3.6/site-packages/rqalpha/utils/logger.py", line 35, in format_exception
    formatted, colored_source = better_exceptions.format_traceback(tb)
AttributeError: module 'better_exceptions' has no attribute 'format_traceback'

**Comment by Cuizi7** [comment]
请安装 0.1.8 版本 better-exceptions。
`pip install better-exceptions==0.1.8`
