### ISSUE TITLE
pkg_resources.DistributionNotFound

### ISSUE THREAD

**Issue by lw5885799** [ricequant/rqalpha#256]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：
刚搭建完环境  没有使用conda的虚拟环境 有大神能帮忙看下么
## 1. RQAlpha的版本
3.0.9
## 2. Python的版本
3.6.3
## 3. 是Windows/Linux/MacOS or others?
WIN10
## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
run -f ./rqalpha/examples/buy_and_hold.py -s 2016-06-01 -e 2016-12-01 --stock-starting-cash 100000 --benchmark 000300.XSHG --plot
## 5. 您出现的错误堆栈日志信息
/home/rq/anaconda3/envs/untitled/bin/python /home/rqalpha.py run -f ./rqalpha/examples/buy_and_hold.py -s 2016-06-01 -e 2016-12-01 --stock-starting-cash 100000 --benchmark 000300.XSHG --plot
Traceback (most recent call last):
  File "/home/rqalpha.py", line 4, in <module>
    from pkg_resources import load_entry_point
  File "/home/rq/anaconda3/envs/untitled/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3147, in <module>
    @_call_aside
  File "/home/rq/anaconda3/envs/untitled/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3131, in _call_aside
    f(*args, **kwargs)
  File "/home/rq/anaconda3/envs/untitled/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3160, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/rq/anaconda3/envs/untitled/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in _build_master
    ws.require(__requires__)
  File "/home/rq/anaconda3/envs/untitled/lib/python3.6/site-packages/pkg_resources/__init__.py", line 984, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/rq/anaconda3/envs/untitled/lib/python3.6/site-packages/pkg_resources/__init__.py", line 870, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'rqalpha' distribution was not found and is required by the application

Process finished with exit code 1

**Comment by hzliu** [comment]
你是怎么安装的？看起来rqalpha没有正常安装
