### ISSUE TITLE
在尝试用jupyter nootebook上做回测时出现了问题，希望大神来解决 :)

### ISSUE THREAD

**Issue by KunXie** [ricequant/rqalpha#259]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

## 1. RQAlpha的版本
(3, 0, 9)

## 2. Python的版本
Python 3.6.3 :: Anaconda custom (64-bit)

## 3. 是Windows/Linux/MacOS or others?
MacOS EI Capital 10.11.6
使用的是 jupyter notebook：5.2.2

## 4. 您出现问题对应的源码

    %%rqalpha -s 20170101 -e 20170220 -p -bm 000001.XSHG --account stock 100000

    def init(context):
        pass
    def before_trading(context):
        pass
    def handle_bar(context, bar_dict):
        print('hello world')
    def after_trading(context):
        pass

## 5. 您出现的错误堆栈日志信息
2017-01-03 INFO hello world
2017-01-04 INFO hello world
2017-01-05 INFO hello world
2017-01-06 INFO hello world
2017-01-09 INFO hello world
2017-01-10 INFO hello world
2017-01-11 INFO hello world
2017-01-12 INFO hello world
2017-01-13 INFO hello world
2017-01-16 INFO hello world
2017-01-17 INFO hello world
2017-01-18 INFO hello world
2017-01-19 INFO hello world
2017-01-20 INFO hello world
2017-01-23 INFO hello world
2017-01-24 INFO hello world
2017-01-25 INFO hello world
2017-01-26 INFO hello world
2017-02-03 INFO hello world
2017-02-06 INFO hello world
2017-02-07 INFO hello world
2017-02-08 INFO hello world
2017-02-09 INFO hello world
2017-02-10 INFO hello world
2017-02-13 INFO hello world
2017-02-14 INFO hello world
2017-02-15 INFO hello world
2017-02-16 INFO hello world
2017-02-17 INFO hello world
2017-02-20 INFO hello world
[2018-02-24 23:04:22.918233] ERROR: system_log: tear down fail for sys_analyser
Traceback (most recent call last):
  File "/Users/KunXie/anaconda3/lib/python3.6/site-packages/rqalpha/mod/__init__.py", line 77, in tear_down
    ret = self._mod_dict[mod_name].tear_down(*args)
  File "/Users/KunXie/anaconda3/lib/python3.6/site-packages/rqalpha/mod/rqalpha_mod_sys_analyser/mod.py", line 277, in tear_down
    plot_result(result_dict, self._mod_config.plot, self._mod_config.plot_save_file)
  File "/Users/KunXie/anaconda3/lib/python3.6/site-packages/rqalpha/mod/rqalpha_mod_sys_analyser/plot.py", line 57, in plot_result
    portfolio_value = portfolio.unit_net_value * portfolio.units
  File "/Users/KunXie/anaconda3/lib/python3.6/site-packages/pandas/core/ops.py", line 739, in wrapper
  File "/Users/KunXie/anaconda3/lib/python3.6/site-packages/pandas/core/ops.py", line 700, in safe_na_op
    left, right = _align_method_SERIES(left, right)
  File "/Users/KunXie/anaconda3/lib/python3.6/site-packages/pandas/core/ops.py", line 673, in na_op
  File "/Users/KunXie/anaconda3/lib/python3.6/site-packages/pandas/core/computation/expressions.py", line 12, in <module>
    from pandas.core.computation import _NUMEXPR_INSTALLED
ImportError: cannot import name '_NUMEXPR_INSTALLED'

**Comment by hzliu** [comment]
看起来是 pandas 安装有问题？

**Comment by Cuizi7** [comment]
no reply, closed.
