### ISSUE TITLE
回测日期太早会出现exception

### ISSUE THREAD

**Issue by szhu3210** [ricequant/rqalpha#265]
命令用的文档中的例子（ http://rqalpha.readthedocs.io/zh_CN/latest/intro/overview.html#id8 ），原来的命令运行成功，但是修改了回测开始时间（貌似2006年以前都会出现exception）后，出现exception。

## 1. RQAlpha的版本
a7b68c6

## 2. Python的版本
3.6.4

## 3. 是Windows/Linux/MacOS or others?
MacOS

## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
` rqalpha run -f rsi.py -s 2006-01-01 -e 2018-01-01 -o result.pkl --plot --progress --account stock 100000`

## 5. 您出现的错误堆栈日志信息
`
Traceback (most recent call last):
  File "/Users/troy/Library/Python/3.6/lib/python/site-packages/rqalpha/core/strategy.py", line 84, in handle_bar
    self._handle_bar(self._user_context, bar_dict)
  File "rsi.py", line 38, in handle_bar
    rsi_data = talib.RSI(prices, timeperiod=context.TIME_PERIOD)[-1]
  File "talib/_func.pxi", line 9661, in talib._ta_lib.RSI
Exception: inputs are all NaN

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/troy/Library/Python/3.6/lib/python/site-packages/rqalpha/main.py", line 298, in run
    Executor(env).run(bar_dict)
  File "/Users/troy/Library/Python/3.6/lib/python/site-packages/rqalpha/core/executor.py", line 65, in run
    event_bus.publish_event(event)
  File "/Users/troy/Library/Python/3.6/lib/python/site-packages/rqalpha/events.py", line 43, in publish_event
    if l(event):
  File "/Users/troy/Library/Python/3.6/lib/python/site-packages/rqalpha/utils/__init__.py", line 181, in wrapper
    return func(*args, **kwargs)
  File "/Users/troy/Library/Python/3.6/lib/python/site-packages/rqalpha/core/strategy.py", line 84, in handle_bar
    self._handle_bar(self._user_context, bar_dict)
  File "/Users/troy/Library/Python/3.6/lib/python/site-packages/rqalpha/execution_context.py", line 95, in __exit__
    raise user_exc
rqalpha.utils.exception.CustomException: Traceback (most recent call last):
  File rsi.py, line 38 in handle_bar
    rsi_data = talib.RSI(prices, timeperiod=context.TIME_PERIOD)[-1]
    --> target_available_cash = 30000.0
    --> cur_position = 0
    --> rsi_data = 71.111111111111086
    --> prices = array([], dtype=float64)
    --> stock = '601988.XSHG'
    --> bar_dict = BarMap()
    --> context = Context({s1 = '000001.XSHE', s2 = '601988.XSHG', s3 = '000068.XSHE', stocks = ['000001.XSHE', '601988.XSHG', '000068.XSHE'], TIME_PERIOD = 14, HIGH_RSI = 85, LO ...

Exception: inputs are all NaN

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/troy/Library/Python/3.6/bin/rqalpha", line 11, in <module>
    sys.exit(entry_point())
  File "/Users/troy/Library/Python/3.6/lib/python/site-packages/rqalpha/__main__.py", line 70, in entry_point
    cli(obj={})
  File "/Users/troy/Library/Python/3.6/lib/python/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/troy/Library/Python/3.6/lib/python/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/troy/Library/Python/3.6/lib/python/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/troy/Library/Python/3.6/lib/python/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/troy/Library/Python/3.6/lib/python/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/troy/Library/Python/3.6/lib/python/site-packages/rqalpha/__main__.py", line 126, in run
    results = main.run(cfg, source_code=source_code)
  File "/Users/troy/Library/Python/3.6/lib/python/site-packages/rqalpha/main.py", line 306, in run
    code = _exception_handler(e)
  File "/Users/troy/Library/Python/3.6/lib/python/site-packages/rqalpha/main.py", line 326, in _exception_handler
    better_exceptions.excepthook(e.error.exc_type, e.error.exc_val, e.error.exc_tb)
  File "/Users/troy/Library/Python/3.6/lib/python/site-packages/better_exceptions/__init__.py", line 53, in excepthook
    formatted = format_exception(exc, value, tb)
  File "/Users/troy/Library/Python/3.6/lib/python/site-packages/rqalpha/utils/logger.py", line 35, in format_exception
    formatted, colored_source = better_exceptions.format_traceback(tb)
AttributeError: module 'better_exceptions' has no attribute 'format_traceback'`

**Comment by hzliu** [comment]
应该是你选取的股票上市天数不够

2018-03-11 14:27 GMT+08:00 Shengxiang Zhu (Troy) <notifications@github.com>:
