### ISSUE TITLE
请帮忙解答一下

### ISSUE THREAD

**Issue by rhermit** [ricequant/rqalpha#274]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

**Comment by rhermit** [comment]
rqalpha 版本3.0.9
Python2.7
Windows
运行run_code_demo.py和run_file_demo.py和run_func_demo.py
会出现
Traceback (most recent call last):
  File "C:/RQalpha-3.0.9/rqalpha/examples/run_code_demo.py", line 47, in <module>
    run_code(code, config)
  File "C:\RQalpha-3.0.9\rqalpha\__init__.py", line 115, in run_code
    return main.run(config, source_code=code)
  File "C:\RQalpha-3.0.9\rqalpha\main.py", line 315, in run
    code = _exception_handler(user_exc)
  File "C:\RQalpha-3.0.9\rqalpha\main.py", line 326, in _exception_handler
    better_exceptions.excepthook(e.error.exc_type, e.error.exc_val, e.error.exc_tb)
  File "C:\Anaconda2\lib\site-packages\better_exceptions\__init__.py", line 53, in excepthook
    formatted = format_exception(exc, value, tb)
  File "C:\RQalpha-3.0.9\rqalpha\utils\logger.py", line 35, in format_exception
    formatted, colored_source = better_exceptions.format_traceback(tb)
AttributeError: 'module' object has no attribute 'format_traceback'

Process finished with exit code 1

**Comment by Cuizi7** [comment]
解决方法见https://github.com/ricequant/rqalpha/issues/245
