### ISSUE TITLE
安装mod不支持pip10.0以上 'cannot import name main'

### ISSUE THREAD

**Issue by yousiku** [ricequant/rqalpha#307]
RQAlpha3.0.9
Python3.5.4
Windows7

在安装mod执行命令'rqalpha mod install -e .'报错：

> Traceback (most recent call last):
  File "c:\program files\anaconda3\envs\rqalpha\lib\runpy.py", line 193, in _run
_module_as_main
    "__main__", mod_spec)
  File "c:\program files\anaconda3\envs\rqalpha\lib\runpy.py", line 85, in _run_
code
    exec(code, run_globals)
  File "C:\Program Files\Anaconda3\envs\rqalpha\Scripts\rqalpha.exe\__main__.py"
, line 9, in <module>
  File "c:\program files\anaconda3\envs\rqalpha\lib\site-packages\rqalpha\__main
__.py", line 70, in entry_point
    cli(obj={})
  File "c:\program files\anaconda3\envs\rqalpha\lib\site-packages\click\core.py"
, line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\program files\anaconda3\envs\rqalpha\lib\site-packages\click\core.py"
, line 697, in main
    rv = self.invoke(ctx)
  File "c:\program files\anaconda3\envs\rqalpha\lib\site-packages\click\core.py"
, line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\program files\anaconda3\envs\rqalpha\lib\site-packages\click\core.py"
, line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\program files\anaconda3\envs\rqalpha\lib\site-packages\click\core.py"
, line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\program files\anaconda3\envs\rqalpha\lib\site-packages\rqalpha\__main
__.py", line 367, in mod
    locals()[cmd](params)
  File "c:\program files\anaconda3\envs\rqalpha\lib\site-packages\rqalpha\__main
__.py", line 225, in install
    from pip import main as pip_main
ImportError: cannot import name 'main'

判断是由于pip10.0之后的版本不支持from pip import main的用法，望确认

**Comment by Cuizi7** [comment]
fixed in master branch
