### ISSUE TITLE
策略中不能 pickle 自定义类型的对象

### ISSUE THREAD

**Issue by Cuizi7** [ricequant/rqalpha#337]
example:

```python
import pickle

def init(context):
    context.t = Test()

def handle_bar(context, bar_dict):
    print(pickle.dumps(context.t))

class Test():
    pass

```

exception:

```
[2018-06-07 11:24:11.770862] INFO: system_log: rqdatac use socket ('rqdatad-pro.ricequant.com', 16004)
Traceback (most recent call last):
  File "/Users/cuiziqi/OneDrive/Workspace/rqalpha/rqalpha/core/strategy.py", line 84, in handle_bar
    self._handle_bar(self._user_context, bar_dict)
    │                │                   └ BarMap()
    │                └ <rqalpha.core.strategy.Strategy object at 0x126d66d30>
    └ <rqalpha.core.strategy.Strategy object at 0x126d66d30>
  File "/Users/cuiziqi/.rqpro/strategy/strategy.py", line 9, in handle_bar
    print(pickle.dumps(context.t))
    │     │            └ Context({t = <rqalpha.user_module.Test object at 0x126d66f28>})
    │     └ <module 'pickle' from '/Applications/RQPro.app/Contents/rqalpha/lib/python3.5/pickle.py'>
    └ <function user_print at 0x10820c598>
_pickle.PicklingError: Can't pickle <class 'rqalpha.user_module.Test'>: attribute lookup Test on rqalpha.user_module failed

```

**Comment by Cuizi7** [comment]
master 分支已支持在模拟交易和实盘中 pickle 自定义类型的对象。
