### ISSUE TITLE
clone到本地后运行扩展数据源例子， 自有数据源的问题

### ISSUE THREAD

**Issue by luhongkai** [ricequant/rqalpha#368]
## 1. RQAlpha的版本
最新
## 2. Python的版本
3.6
## 3. 是Windows/Linux/MacOS or others?
win

## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
我把rqalpha clone到本地，配置好环境后，运行官方文档扩展数据源的代码例子 test_extend_api，
报错：
2018-08-21 ERROR [Errno 2] No such file or directory: 'C:\\Users\\Administrator/.rqalpha\\bundle\\stocks.bcolz\\meta\\sizes'
[2018-08-21 16:51:57.295604] ERROR: system_log: 策略运行产生异常

我理解这个错误是缺少官方提供下载的二进制数据，
不过这个扩展数据源的例子不是为了能用自己的本地数据源的吗？
文档中例子最后一句话“我们就可以直接在策略中使用 get_csv_as_df 函数了”，并不能直接调用？
总觉得缺少了一部分调用的code，
一个完整的可以自由调用自有数据源例子应该是什么样的？谢谢

## 5. 您出现的错误堆栈日志信息
Traceback (most recent call last):

  File "D:\rqalpha\rqalpha\main.py", line 207, in run
    env.set_data_source(BaseDataSource(config.base.data_bundle_path))

  File "D:\rqalpha\rqalpha\data\base_data_source.py", line 52, in __init__
    DayBarStore(_p('stocks.bcolz'), StockBarConverter),

  File "D:\rqalpha\rqalpha\data\daybar_store.py", line 26, in __init__
    self._table = bcolz.open(main, 'r')

  File "D:\Anaconda3\lib\site-packages\bcolz\toplevel.py", line 140, in open
    return bcolz.carray(rootdir=rootdir, mode=mode)

  File "carray_ext.pyx", line 1067, in bcolz.carray_ext.carray.__cinit__

  File "carray_ext.pyx", line 1369, in bcolz.carray_ext.carray._read_meta

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Administrator/.rqalpha\\bundle\\stocks.bcolz\\meta\\sizes'

2018-08-21 ERROR [Errno 2] No such file or directory: 'C:\\Users\\Administrator/.rqalpha\\bundle\\stocks.bcolz\\meta\\sizes'
[2018-08-21 16:51:57.295604] ERROR: system_log: 策略运行产生异常
[2018-08-21 16:51:57.311605] DEBUG: basic_system_log: mod tear_down [START] extend_api_demo
[2018-08-21 16:51:57.327606] DEBUG: basic_system_log: mod tear_down [END]   extend_api_demo
[2018-08-21 16:51:57.361608] DEBUG: basic_system_log: mod tear_down [START] sys_analyser
[2018-08-21 16:51:57.378609] DEBUG: basic_system_log: mod tear_down [END]   sys_analyser
[2018-08-21 16:51:57.394609] DEBUG: basic_system_log: mod tear_down [START] sys_risk
[2018-08-21 16:51:57.410610] DEBUG: basic_system_log: mod tear_down [END]   sys_risk
[2018-08-21 16:51:57.446612] DEBUG: basic_system_log: mod tear_down [START] sys_progress
[2018-08-21 16:51:57.462613] DEBUG: basic_system_log: mod tear_down [END]   sys_progress
[2018-08-21 16:51:57.478614] DEBUG: basic_system_log: mod tear_down [START] sys_simulation
[2018-08-21 16:51:57.494615] DEBUG: basic_system_log: mod tear_down [END]   sys_simulation
[2018-08-21 16:51:57.510616] DEBUG: basic_system_log: mod tear_down [START] sys_accounts
[2018-08-21 16:51:57.547618] DEBUG: basic_system_log: mod tear_down [END]   sys_accounts

**Comment by luhongkai** [comment]
我的code:
from rqalpha.api import *
from rqalpha import run_code

code = """
def init(context):
    IF1706_df = get_csv_as_df()
    context.IF1706_df = IF1706_df


def before_trading(context):
    logger.info(context.IF1706_df)

def handle_bar(context):
    pass
"""

__config__ = {
    "base": {
        "start_date": "2015-01-09",
        "end_date": "2015-01-10",
        "frequency": "1d",
        "matching_type": "current_bar",
        "benchmark": None,
        "accounts": {
            "future": 1000000
        }
    },
    "extra": {
        "log_level": "verbose",
    },
    "mod": {
        "extend_api_demo": {
            "enabled": True,
            "lib": "rqalpha.examples.extend_api.rqalpha_mod_extend_api_demo",
            "csv_path": "../IF1706_20161108.csv"
        }
    }
}

run_code(code, __config__)

**Comment by luhongkai** [comment]
已经可以读本地数据了，后面学习怎么在handle_bar里用rqalpha API计算自有数据发出信号并回测的方法

**Comment by Cuizi7** [comment]
上述报错是 BaseDataSource 报出来的，您需要实现对接自有数据源的 DataSource 并且替换掉 BaseDataSource 方可不依赖 bundle 数据。
