### ISSUE TITLE
rqalpha  update_bundle，git pull之后还是有这个提示： data bundle not found. Run `python3 {baseProject}/tools/create_bundle` to download data bundle.

### ISSUE THREAD

**Issue by FallacyWalker** [ricequant/rqalpha#37]
运行时异常
/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 /DeepLink/LocalRqalphaDevelop/rqalpha/rqalpha run -f buy_and_hold.py -s 2016-01-01 -e 2016-11-20 -o result.pkl --plot
data bundle not found. Run `python3 {baseProject}/tools/create_bundle` to download data bundle.
data bundle not found. Run `python3 {baseProject}/tools/create_bundle` to download data bundle.
Traceback (most recent call last):
  File "/DeepLink/LocalRqalphaDevelop/rqalpha/rqalpha/main.py", line 149, in run
    mod_handler = ModHandler(env)
  File "/DeepLink/LocalRqalphaDevelop/rqalpha/rqalpha/mod/mod_handler.py", line 29, in __init__
    for mod_name in config.mod.__dict__:
AttributeError: 'NoneType' object has no attribute 'mod'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/DeepLink/LocalRqalphaDevelop/rqalpha/rqalpha/__main__.py", line 187, in <module>
    entry_point()
  File "/DeepLink/LocalRqalphaDevelop/rqalpha/rqalpha/__main__.py", line 45, in entry_point
    cli(obj={})
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/DeepLink/LocalRqalphaDevelop/rqalpha/rqalpha/__main__.py", line 93, in run
    main.run(parse_config(kwargs, config_path))
  File "/DeepLink/LocalRqalphaDevelop/rqalpha/rqalpha/main.py", line 317, in run
    user_exc = create_custom_exception(exc_type, exc_val, exc_tb, config.base.strategy_file)
AttributeError: 'NoneType' object has no attribute 'base'

**Comment by wh1100717** [comment]
请更新RQAlpha 至最新版再试一下。
