### ISSUE TITLE
RQAlpha目前不支持多线程，请问是否适合改成多线程？

### ISSUE THREAD

**Issue by jackeylu** [ricequant/rqalpha#372]
我希望在Linux服务器上部署RQAlpha，让其能够作为后台服务进程，同时服务多个回测请求。
但是我发现改成多个子线程执行回测时，会存在资源使用混乱的情况（具体见下文）。

**请问如果要让RQAlpha支持多个回测同时进行并利用好服务器的CPU资源，有什么建议和思路吗？谢谢**

## 1. RQAlpha的版本
In [1]: from rqalpha import version_info

In [2]: version_info
Out[2]: (3, 1, 1, 'b7af7e')

## 2. Python的版本
Python 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 12:30:02) [MSC v.1900 64 bit (AMD64)]

## 3. 是Windows/Linux/MacOS or others?
Windows/Linux都有同样的现象。

## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置

我写了一个多线程的主程序（`threaded-coroutines.py`），master读取redis中的任务，然后向3个worker线程分配回测任务。
辅助程序`submitter.py`向redis中写入任务。

当worker线程多于1个时，将会出现异常，提示ExecutionContext.stack中pop出来的对象不是合适的Context。

[threaded-example.zip](https://github.com/ricequant/rqalpha/files/2359838/threaded-example.zip)

## 5. 您出现的错误堆栈日志信息

```
b"(0, '000001.XSHE')"
0 000001.XSHE
Waiting  0
b"(1, '000001.XSHG')"
1 000001.XSHG
Waiting  1
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Users\ME\codes\quantor\rqalpha-official\rqalpha\main.py", line 320, in run
  File "C:\Users\ME\codes\quantor\rqalpha-official\rqalpha\main.py", line 320, in run
        executor.run(bar_dict)
  File "C:\Users\ME\codes\quantor\rqalpha-official\rqalpha\core\executor.py", line 98, in run
executor.run(bar_dict)
  File "C:\Users\ME\codes\quantor\rqalpha-official\rqalpha\core\executor.py", line 98, in run
    event_bus.publish_event(event)    
  File "C:\Users\ME\codes\quantor\rqalpha-official\rqalpha\events.py", line 43, in publish_event
event_bus.publish_event(event)
  File "C:\Users\ME\codes\quantor\rqalpha-official\rqalpha\events.py", line 43, in publish_event
    if listener(event):
      File "C:\Users\ME\codes\quantor\rqalpha-official\rqalpha\utils\__init__.py", line 182, in wrapper
if listener(event):
  File "C:\Users\ME\codes\quantor\rqalpha-official\rqalpha\utils\__init__.py", line 182, in wrapper
        return func(*args, **kwargs)
  File "C:\Users\ME\codes\quantor\rqalpha-official\rqalpha\core\strategy.py", line 90, in handle_bar
return func(*args, **kwargs)
  File "C:\Users\ME\codes\quantor\rqalpha-official\rqalpha\core\strategy.py", line 90, in handle_bar
    self._handle_bar(self._user_context, bar_dict)
  File "C:\Users\ME\codes\quantor\rqalpha-official\rqalpha\execution_context.py", line 78, in __exit__
    self._handle_bar(self._user_context, bar_dict)    self._pop()
  File "C:\Users\ME\codes\quantor\rqalpha-official\rqalpha\execution_context.py", line 78, in __exit__

  File "C:\Users\ME\codes\quantor\rqalpha-official\rqalpha\execution_context.py", line 66, in _pop
    self._pop()
  File "C:\Users\ME\codes\quantor\rqalpha-official\rqalpha\execution_context.py", line 66, in _pop
    raise RuntimeError("Popped wrong context")
RuntimeError    : raise RuntimeError("Popped wrong context")
RuntimeError: Popped wrong context
2012-06-18 ERROR Popped wrong context
Popped wrong context[2018-09-07 14:31:56.403656] ERROR: system_log: 策略运行产生异常

2012-06-18 ERROR Popped wrong context
[2018-09-07 14:31:56.404653] ERROR: system_log: 策略运行产生异常
Done  0  with OK.
Done 0 with OK.
Done  1  with OK.
Done 1 with OK.
```

**Comment by Cuizi7** [comment]
建议把策略放在不同的进程中运行。本身使用python的多线程对于提升CPU利用率并没有什么帮助。

**Comment by Cuizi7** [comment]
我们自己在生产环境的做法是每个策略运行在单独的docker容器中。

**Comment by jackeylu** [comment]
@Cuizi7 谢谢您的建议。请问你们生产环境里用的回测引擎与RQAlpha相比，在data source的加载上是怎么处理？有使用同一份内存中的data source作为多个docker中的RQAlpha实例共同使用吗？

我感觉，无论是多进程，或者是docker内启动RQAlpha都稍微有点慢，应该是慢在了data source的加载上。如果不同RQAlpha实例中的不同environment实例，可以复用同一份data source实例，是否可行？是否存在着一些资源竞争的问题？

**Comment by akulatatama** [comment]
@jackeylu 我是RIcequant的成员，我们是否可以加个微信详聊？我的是 LiccoLK，搜索微信号即可

**Comment by Cuizi7** [comment]
我们回测使用的RQAlpha与开源版没有太大区别，Datasource对接了更丰富的数据bundle而已，没有在内存中复用datasource(因为还要考虑策略安全等问题)，我们通过使用ssd等方法发现大多数时候性能瓶颈不在行情数据的io。
当然模拟交易和实盘我们有不同的实现，方便的话可以留个微信详细交流，或者直接加楼上微信。

**Comment by jackeylu** [comment]
谢谢 @Cuizi7 @akulatatama 。我加你们微信再聊。这里close掉这个issue吧。
