### ISSUE TITLE
ValueError: could not convert string to Timestamp

### ISSUE THREAD

**Issue by FallacyWalker** [ricequant/rqalpha#39]
/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 /DeepLink/LocalRqalphaNew/rqalpha/rqalpha/ run -f rsi.py -s 2016-01-01 -e 2016-11-20 -stock-starting-cash 100000 -o result.pkl --plot
Traceback (most recent call last):
  File "pandas/tslib.pyx", line 1588, in pandas.tslib.convert_str_to_tsobject (pandas/tslib.c:29408)
  File "pandas/src/datetime.pxd", line 135, in datetime._string_to_dts (pandas/tslib.c:95676)
ValueError: Error parsing datetime string "tock-starting-cash" at position 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pandas/tslib.pyx", line 1608, in pandas.tslib.convert_str_to_tsobject (pandas/tslib.c:29833)
  File "pandas/tslib.pyx", line 1974, in pandas.tslib.parse_datetime_string (pandas/tslib.c:35434)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/dateutil/parser.py", line 1168, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/dateutil/parser.py", line 559, in parse
    raise ValueError("Unknown string format")
ValueError: Unknown string format

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/DeepLink/LocalRqalphaNew/rqalpha/rqalpha/__main__.py", line 218, in <module>
    entry_point()
  File "/DeepLink/LocalRqalphaNew/rqalpha/rqalpha/__main__.py", line 44, in entry_point
    cli(obj={})
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 1064, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 621, in make_context
    self.parse_args(ctx, args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 880, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 1396, in handle_parse_result
    value = self.full_process_value(ctx, value)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 1681, in full_process_value
    return Parameter.full_process_value(self, ctx, value)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 1365, in full_process_value
    value = self.process_value(ctx, value)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 1355, in process_value
    return self.type_cast_value(ctx, value)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 1344, in type_cast_value
    return _convert(value, (self.nargs != 1) + bool(self.multiple))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 1342, in _convert
    return self.type(value, self, ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/types.py", line 38, in __call__
    return self.convert(value, param, ctx)
  File "/DeepLink/LocalRqalphaNew/rqalpha/rqalpha/utils/click_helper.py", line 27, in convert
    return pd.Timestamp(value)
  File "pandas/tslib.pyx", line 407, in pandas.tslib.Timestamp.__new__ (pandas/tslib.c:10447)
  File "pandas/tslib.pyx", line 1472, in pandas.tslib.convert_to_tsobject (pandas/tslib.c:27555)
  File "pandas/tslib.pyx", line 1611, in pandas.tslib.convert_str_to_tsobject (pandas/tslib.c:29886)
ValueError: could not convert string to Timestamp

Process finished with exit code 1

**Comment by wh1100717** [comment]
@FallacyWalker 参数是 `--stock-starting-cash`  不是 `-stock-starting-cash`
