### ISSUE TITLE
最新版本的rqalpha quotation-server redis://localhost/1 报错

### ISSUE THREAD

**Issue by jxhuliqun138** [ricequant/rqalpha#417]
## 3. 是Windows

D:\res\rqalpha-mod-stock-realtime-master>rqalpha quotation-server redis://localhost/1
[2019-03-15 21:34:27.781582] ERROR: system_log: in parse_user_config, exception: [Errno 2] No such file or directory: 'strategy.py'
Traceback (most recent call last):
  File "D:\Anaconda35\Scripts\rqalpha-script.py", line 11, in <module>
    load_entry_point('rqalpha==3.3.1', 'console_scripts', 'rqalpha')()
  File "D:\Anaconda35\lib\site-packages\rqalpha\__main__.py", line 71, in entry_point
    cli(obj={})
  File "D:\Anaconda35\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "D:\Anaconda35\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "D:\Anaconda35\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\Anaconda35\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Anaconda35\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "D:\Anaconda35\lib\site-packages\rqalpha_mod_stock_realtime-0.0.1-py3.5.egg\rqalpha_mod_stock_realtime\__init__.py", line 73, in quotation_server
    data_proxy = DataProxy(data_source)
TypeError: __init__() missing 1 required positional argument: 'price_board'

**Comment by Cuizi7** [comment]
rqalpha-mod-stock-realtime 已不再维护
