### ISSUE TITLE
在Python2环境下运行示例报错rqalpha run -f E:\rqalpha\buy_and_hold.py -s 2013-01-01 -e 2015-01-01 --plot

### ISSUE THREAD

**Issue by lzhw520110** [ricequant/rqalpha#42]
[Anaconda2] C:\Users\thinkpad>rqalpha run -f E:\rqalpha\buy_and_hold.py -s 2013-01-01 -e 2015-01-01 --plot
Traceback (most recent call last):
  File "c:\users\thinkpad\anaconda2\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\users\thinkpad\anaconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\thinkpad\Anaconda2\Scripts\rqalpha.exe\__main__.py", line 9, in <module>
  File "c:\users\thinkpad\anaconda2\lib\site-packages\rqalpha\__main__.py", line 44, in entry_point
    cli(obj={})
  File "c:\users\thinkpad\anaconda2\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\thinkpad\anaconda2\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\thinkpad\anaconda2\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\thinkpad\anaconda2\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\thinkpad\anaconda2\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\thinkpad\anaconda2\lib\site-packages\rqalpha\__main__.py", line 115, in run
    locale.setlocale(locale.LC_ALL, "en_US.UTF-8")
  File "c:\users\thinkpad\anaconda2\lib\locale.py", line 579, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

**Comment by wh1100717** [comment]
已解决  请升级至0.3.2 及以上版本
