### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by myz8110** [ricequant/rqalpha#445]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

## 1. RQAlpha的版本
3.2.0
## 2. Python的版本
3.6.0
## 3. 是Windows/Linux/MacOS or others?
windows
## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
D:\Anaconda3\python.exe D:/Anaconda3/start.py run -f D:\Anaconda3\examples\myfiles\lm.py
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\rqalpha\main.py", line 211, in run
    env.set_data_source(BaseDataSource(config.base.data_bundle_path))
  File "D:\Anaconda3\lib\site-packages\rqalpha\data\base_data_source.py", line 57, in __init__
    self._instruments = InstrumentStore(_p('instruments.pk'))
  File "D:\Anaconda3\lib\site-packages\rqalpha\data\instrument_store.py", line 26, in __init__
    self._instruments = [Instrument(i) for i in d]
  File "D:\Anaconda3\lib\site-packages\rqalpha\data\instrument_store.py", line 26, in <listcomp>
    self._instruments = [Instrument(i) for i in d]
  File "D:\Anaconda3\lib\site-packages\rqalpha\model\instrument.py", line 44, in __init__
    self._ins_dict["listed_date"] = self._fix_date(dic["listed_date"], self.DEFAULT_LISTED_DATE)
  File "D:\Anaconda3\lib\site-packages\rqalpha\model\instrument.py", line 35, in _fix_date
    year, month, day = ds.split('-')
AttributeError: 'datetime.datetime' object has no attribute 'split'
2019-08-21 ERROR 'datetime.datetime' object has no attribute 'split'
[2019-08-21 21:22:15.903014] ERROR: system_log: 策略运行产生异常

**Comment by Cuizi7** [comment]
更新 rqalpha 版本
