### ISSUE TITLE
调用 rqalpha mod uninstall -e . ，出现以下错误

### ISSUE THREAD

**Issue by chenyun90323** [ricequant/rqalpha#454]
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\Scripts\rqalpha-script.py", line 11, in <module>
    load_entry_point('rqalpha', 'console_scripts', 'rqalpha')()
  File "e:\github\rqalpha\rqalpha\__main__.py", line 73, in entry_point
    cli(obj={})
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "e:\github\rqalpha\rqalpha\__main__.py", line 384, in mod
    locals()[cmd](params)
  File "e:\github\rqalpha\rqalpha\__main__.py", line 306, in uninstall
    options, mod_list = UninstallCommand().parse_args(params)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\commands\uninstall.py", line 34, in __init__
    super(UninstallCommand, self).__init__(*args, **kw)
TypeError: __init__() missing 2 required positional arguments: 'name' and 'summary'

**Comment by Cuizi7** [comment]
fixed
