### ISSUE TITLE
运行策略时出现 AttributeError: 'NoneType' object has no attribute 'mod'

### ISSUE THREAD

**Issue by LMdeLiangMi** [ricequant/rqalpha#46]
(E:\Quant_Server\Anaconda) E:\Py_Project\moneyQuant\main\model\quant>rqalpha run -f examples/buy_and_hold.py -d bundle/ -s 2016-06-01 -e 2016-12-01 --stock-starting-cash 100000 --benchmark 000300.XSHG --plot

data bundle not found. Run `rqalpha update_bundle` to download data bundle.
Traceback (most recent call last):
  File "e:\quant_server\anaconda\lib\site-packages\rqalpha\main.py", line 120, in run
    mod_handler = ModHandler(env)
  File "e:\quant_server\anaconda\lib\site-packages\rqalpha\mod\mod_handler.py", line 30, in __init__
    for mod_name in config.mod.__dict__:
AttributeError: 'NoneType' object has no attribute 'mod'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\quant_server\anaconda\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\quant_server\anaconda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Quant_Server\Anaconda\Scripts\rqalpha.exe\__main__.py", line 9, in <module>
  File "e:\quant_server\anaconda\lib\site-packages\rqalpha\__main__.py", line 43, in entry_point
    cli(obj={})
  File "e:\quant_server\anaconda\lib\site-packages\click\core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "e:\quant_server\anaconda\lib\site-packages\click\core.py", line 696, in main
    rv = self.invoke(ctx)
  File "e:\quant_server\anaconda\lib\site-packages\click\core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "e:\quant_server\anaconda\lib\site-packages\click\core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "e:\quant_server\anaconda\lib\site-packages\click\core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "e:\quant_server\anaconda\lib\site-packages\rqalpha\__main__.py", line 133, in run
    main.run(parse_config(kwargs, config_path))
  File "e:\quant_server\anaconda\lib\site-packages\rqalpha\main.py", line 288, in run
    user_exc = create_custom_exception(exc_type, exc_val, exc_tb, config.base.strategy_file)
AttributeError: 'NoneType' object has no attribute 'base'

**Comment by LMdeLiangMi** [comment]
把bundle和examples放到quant目录下

cd E:\Py_Project\moneyQuant\main\model\quant
rqalpha run -f examples/buy_and_hold.py -d . -s 2016-06-01 -e 2016-12-01 --stock-starting-cash 100000 --benchmark 000300.XSHG --plot

问题解决
