### ISSUE TITLE
Mac Python2.7环境下安装失败

### ISSUE THREAD

**Issue by haogefeifei** [ricequant/rqalpha#47]
```
➜  rqalpha git:(master) sudo pip install setuptools 
The directory '/Users/aaa/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/aaa/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting setuptools
  Downloading setuptools-34.2.0-py2.py3-none-any.whl (389kB)
    100% |████████████████████████████████| 399kB 396kB/s 
Requirement already satisfied: appdirs>=1.4.0 in /Library/Python/2.7/site-packages (from setuptools)
Requirement already satisfied: packaging>=16.8 in /Library/Python/2.7/site-packages (from setuptools)
Requirement already satisfied: six>=1.6.0 in /Library/Python/2.7/site-packages (from setuptools)
Requirement already satisfied: pyparsing in /Library/Python/2.7/site-packages (from packaging>=16.8->setuptools)
Installing collected packages: setuptools
Successfully installed setuptools-34.2.0
➜  rqalpha git:(master) sudo python setup.py install 
Traceback (most recent call last):
  File "setup.py", line 22, in <module>
    from setuptools import (
  File "/Library/Python/2.7/site-packages/setuptools/__init__.py", line 12, in <module>
    import setuptools.version
  File "/Library/Python/2.7/site-packages/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 72, in <module>
    import packaging.requirements
  File "/Library/Python/2.7/site-packages/packaging/requirements.py", line 59, in <module>
    MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
TypeError: __call__() takes exactly 2 arguments (1 given)

```

**Comment by haogefeifei** [comment]
pip install setuptools==33.1.1 后装上了

setuptools要指定版本才行，我更新的setuptools-34.2.0会报错

**Comment by wh1100717** [comment]
@haogefeifei 我这里使用setuptools-34.2.0 安装正常啊 没有重现

**Comment by wh1100717** [comment]
@haogefeifei 分别在windows 上 和 mac 上 都测试了 34.2.0 版本...

**Comment by haogefeifei** [comment]
这就不清楚了。。关了吧。。 我换了个setuptools其实可以了，可能是下面依赖的问题
