### ISSUE TITLE
MOD教程运行发生错误

### ISSUE THREAD

**Issue by liugang7** [ricequant/rqalpha#470]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

## 1. RQAlpha的版本
3.4.4

## 2. Python的版本
3.7.6
## 3. 是Windows/Linux/MacOS or others?
Windows 10 64bit
VS code
## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置
A。在MOD教程里面，https://rqalpha.readthedocs.io/zh_CN/latest/development/mod.html
，完全按照教程操作，创建MOD的相关目录和文件。

B。完成以后在powershell或CMD进入Mod项目的 setup.py 所在路径下进行安装: rqalpha mod install -e . 这个时候，显示错误：'function' object has no attribute 'main'。

C。pip是最新的20.0.2版本。

## 5. 您出现的错误堆栈日志信息

(rqalpha-mod-hello) PS C:\Users\liugw\Documents\PythonProjects\rqalpha-mod-hello> rqalpha mod install -e .

Traceback (most recent call last):
  File "C:\Users\liugw\Anaconda3\envs\rqalpha-mod-hello\Scripts\rqalpha-script.py", line 11, in <module>
    load_entry_point('rqalpha==3.4.4', 'console_scripts', 'rqalpha')()
  File "C:\Users\liugw\Anaconda3\envs\rqalpha-mod-hello\lib\site-packages\rqalpha\__main__.py", line 69, in entry_point
    cli(obj={})
  File "C:\Users\liugw\Anaconda3\envs\rqalpha-mod-hello\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\liugw\Anaconda3\envs\rqalpha-mod-hello\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\Users\liugw\Anaconda3\envs\rqalpha-mod-hello\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\liugw\Anaconda3\envs\rqalpha-mod-hello\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\liugw\Anaconda3\envs\rqalpha-mod-hello\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\liugw\Anaconda3\envs\rqalpha-mod-hello\lib\site-packages\rqalpha\__main__.py", line 390, in mod
    locals()[cmd](params)
  File "C:\Users\liugw\Anaconda3\envs\rqalpha-mod-hello\lib\site-packages\rqalpha\__main__.py", line 237, in install
    pip_main = pip_main.main
AttributeError: 'function' object has no attribute 'main'

**Comment by menggangmark** [comment]
同问

**Comment by dxma** [comment]
问题出在__main__.py的install函数，下面最后一行。最新pip已经没有main这个attribute，请将此行直接移到上面try/except import的except部分，如下所示。
<code>
    def install(params):
        """
        Install third-party Mod
        """
        try:
            from pip._internal import main as pip_main
            from pip._internal.commands.install import InstallCommand
        except ImportError:
            from pip import main as pip_main
            from pip.commands.install import InstallCommand
            pip_main = pip_main.main

        if hasattr(InstallCommand, "name"):
            install_command = InstallCommand()
        else:
            install_command = InstallCommand(name='install', summary='Install packages.')
            #pip_main = pip_main.main
</code>

**Comment by Cuizi7** [comment]
4.0.0 版本已移除 rqalpha mod install/uninstall 命令，可以直接使用 pip install/uninstall 安装/卸载 mdo。
