### ISSUE TITLE
想请问一下为何不在AssetPosition中的get_state保存last_price的状态？

### ISSUE THREAD

**Issue by han14466** [ricequant/rqalpha#478]
是不是应该在get_state保存last_price的状态，在set_state中取出这个状态来计算。因为在daily_pnl中算当日盈亏就可以去得到这个值了？目前我看rqalpha的代码是没有保存的。
堆栈信息：
Traceback (most recent call last):
  File "E:\quant\rqalpha\rqalpha\main.py", line 231, in run
    executor.run(bar_dict)
  File "E:\quant\rqalpha\rqalpha\core\executor.py", line 112, in run
    check_before_trading(event)
  File "E:\quant\rqalpha\rqalpha\core\executor.py", line 73, in check_before_trading
    publish_settlement(e)
  File "E:\quant\rqalpha\rqalpha\core\executor.py", line 61, in publish_settlement
    event_bus.publish_event(Event(EVENT.SETTLEMENT))
  File "E:\quant\rqalpha\rqalpha\events.py", line 42, in publish_event
    if listener(event):
  File "E:\quant\rqalpha\rqalpha\mod\rqalpha_mod_sys_accounts\account_model\stock_account.py", line 98, in _on_settlement
    self._static_total_value = super(StockAccount, self).total_value
  File "E:\quant\rqalpha\rqalpha\mod\rqalpha_mod_sys_accounts\account_model\asset_account.py", line 178, in total_value
    return self._static_total_value + self.daily_pnl
  File "E:\quant\rqalpha\rqalpha\mod\rqalpha_mod_sys_accounts\account_model\asset_account.py", line 168, in daily_pnl
    return sum(p.daily_pnl for p in six.itervalues(self._positions))
  File "E:\quant\rqalpha\rqalpha\mod\rqalpha_mod_sys_accounts\account_model\asset_account.py", line 168, in <genexpr>
    return sum(p.daily_pnl for p in six.itervalues(self._positions))
  File "E:\quant\rqalpha\rqalpha\mod\rqalpha_mod_sys_accounts\position_model\asset_position.py", line 312, in daily_pnl
    self._short.trading_pnl - self.transaction_cost
  File "E:\quant\rqalpha\rqalpha\mod\rqalpha_mod_sys_accounts\position_model\asset_position.py", line 122, in trading_pnl
    return self.contract_multiplier * (trade_quantity * self.last_price - self._trade_cost) * self._direction_factor
  File "E:\quant\rqalpha\rqalpha\mod\rqalpha_mod_sys_accounts\position_model\asset_position.py", line 181, in last_price
    raise RuntimeError(_("last price of position {} is not supposed to be nan").format(self._order_book_id))

**Comment by Cuizi7** [comment]
麻烦附上可以复现这个异常的策略代码

**Comment by han14466** [comment]
这个是我用你们realtime做的模拟，如果我的程序断掉，在启动的时候会从persist中读取信息。因为没有persist这个数据所以会报错。
我的代码：
# run_func_demo
from rqalpha.api import *
from rqalpha import run_func

# def on_trade(context, event):
#     # 获取成交信息
#     trade = event.trade
#     if trade.order_book_id == context.s1:
#         with open('/output1.log', 'a') as fp:
#             fp.write('init\n')
#             fp.write(str(trade) + '\n')
#             fp.write(str(context.portfolio)+'\n')
#         print(trade)

def init(context):
    logger.info("init")
    context.s1 = "000001.XSHE"
    update_universe(context.s1)
    context.fired = False

def before_trading(context):
    logger.info("before_trading ")
    pass

def after_trading(context):
    pass


def handle_bar(context, bar_dict):
    # if not context.fired:
    #     # order_percent并且传入1代表买入该股票并且使其占有投资组合的100%
    #     logger.info("start amos handle_bar: " + str(context.s1))
    #     # order_percent(context.s1, 1)
    #     order_shares(context.s1, 100)
    #     context.fired = True

    # order_percent并且传入1代表买入该股票并且使其占有投资组合的100%
    logger.info("start amos handle_bar: " + str(context.s1))
    # order_percent(context.s1, 1)
    order_shares(context.s1, 100)

def handle_tick(context, tick):
    # put all your algorithm main logic here.
    # ...
    logger.info("start amos handle_tick: " + tick.last)
    # ...



config = {
  "base": {
    "start_date": "2018-06-01",
    "end_date": "2020-06-29",
    "frequency": "1m",
    "benchmark": "000300.XSHG",
    "run_type": "p",
    "accounts": {
        "stock": 10000000
    }
  },
  "extra": {
    "log_level": "verbose",
  },
  "mod": {
    "sys_analyser": {
      "enabled": True,
      "output_file": 'amos.pkl',
      "report_save_path": 'realtime.csv',
      "plot": True
    }
  },
  "mod": {
        "stock_realtime": {
            "persist_path": "./persist/strategy/"
        },
        "deepsea_snapshot": {
            "output_path": "./test_mod/"
        }
  }
}

# 您可以指定您要传递的参数
run_func(init=init, after_trading=after_trading, before_trading=before_trading, handle_bar=handle_bar, config=config)

# 如果你的函数命名是按照 API 规范来，则可以直接按照以下方式来运行
# run_func(**globals())

**Comment by Cuizi7** [comment]
模拟交易应实现 PriceBoard 以保证随时可以取到当前正在交易合约的 last_price
