### ISSUE TITLE
跑example里的策略，显示策略运行产生异常

### ISSUE THREAD

**Issue by szuyanghongyu** [ricequant/rqalpha#60]
root@rqalpha-virtual-machine:/home/rqalpha/Documents/examples# rqalpha run -f buy_and_hold.py -s 2015-08-13 -e 2017-03-04 -fc 10000000 -sp 0.0001 -fq 1d -me current_bar --report ./report.f --plot-save /plot.f --plot
2015-08-13 WARN 订单创建失败: 下单量为0。
2015-08-13 ERROR float division by zero
[2017-03-11 01:04:03.122710] ERROR: system_log: 策略运行产生异常
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rqalpha/main.py", line 294, in run
    env.event_bus.publish_event(EVENT.POST_SETTLEMENT)
  File "/usr/local/lib/python3.5/dist-packages/rqalpha/events.py", line 42, in publish_event
    if l(*args, **kwargs):
  File "/usr/local/lib/python3.5/dist-packages/rqalpha/mod/analyser/mod.py", line 74, in _collect_daily
    self._portfolio_daily_returns.append(portfolio.daily_returns)
  File "/usr/local/lib/python3.5/dist-packages/rqalpha/model/account/mixed_account.py", line 70, in daily_returns
    return self.daily_pnl / self._yesterday_portfolio_value
ZeroDivisionError: float division by zero
root@rqalpha-virtual-machine:/home/rqalpha/Documents/examples# 

计算收益曲线时的八阿哥？目前rqalpha0.3.13版

**Comment by wh1100717** [comment]
-fc 表示的的是--future-starting-cash buy_and_hold 策略 交易的是股票。所以您设置了期货，但交易的是股票，所以总账户为0，就会提示这个错误了。把-fc 改成-sc
