### ISSUE TITLE
安装rqalpha之后，执行数据获取命令报错

### ISSUE THREAD

**Issue by batteryhp** [ricequant/rqalpha#67]
我按照[安装指南](http://rqalpha.readthedocs.io/zh_CN/stable/intro/install.html#intro-install)安装好了rqalpha, 执行版本检查
```
[root@centos-ored ~]# rqalpha version
('Current Version: ', (0, 3, 14))
```  
不过，后面执行 `rqalpha update_bundle`时就报错
```
[root@centos-ored ~]# rqalpha update_bundle
Traceback (most recent call last):
  File "/root/anaconda2/bin/rqalpha", line 11, in <module>
    sys.exit(entry_point())
  File "/root/anaconda2/lib/python2.7/site-packages/rqalpha/__main__.py", line 36, in entry_point
    cli(obj={})
  File "/root/anaconda2/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/root/anaconda2/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/root/anaconda2/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/anaconda2/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/anaconda2/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/root/anaconda2/lib/python2.7/site-packages/rqalpha/__main__.py", line 46, in update_bundle
    from . import main
  File "/root/anaconda2/lib/python2.7/site-packages/rqalpha/main.py", line 37, in <module>
    from .data.base_data_source import BaseDataSource
  File "/root/anaconda2/lib/python2.7/site-packages/rqalpha/data/base_data_source.py", line 30, in <module>
    from .daybar_store import DayBarStore
  File "/root/anaconda2/lib/python2.7/site-packages/rqalpha/data/daybar_store.py", line 17, in <module>
    import bcolz
  File "/root/anaconda2/lib/python2.7/site-packages/bcolz/__init__.py", line 51, in <module>
    if dask.__version__ >= LooseVersion(min_dask_version):
  File "/root/anaconda2/lib/python2.7/distutils/version.py", line 296, in __cmp__
    return cmp(self.version, other.version)
AttributeError: 'unicode' object has no attribute 'version'
```  
环境 Centos6.5 python2.7.13(Anaconda 4.3.1)，帮忙看一下？

**Comment by wh1100717** [comment]
@batteryhp 看上去像是bcolz的问题，试一下在ipython里执行执行 `import bcolz` 会不会有这个问题？

**Comment by wh1100717** [comment]
https://github.com/Blosc/bcolz/issues/322 参考一下是否能解决？

**Comment by wh1100717** [comment]
@batteryhp 5天没有回复，先关闭了，如果还有问题再reopen
