### ISSUE TITLE
执行 $ rqalpha disable risk_manager 后  再运行就报错

### ISSUE THREAD

**Issue by bsknight** [ricequant/rqalpha#68]
```bash
root@test2:/usr/local/lib/python2.7/dist-packages/rqalpha# rqalpha disable risk_manager
root@test2:/usr/local/lib/python2.7/dist-packages/rqalpha# rqalpha run -fq 1m -rt p -f 
./examples/golden_cross.py -sc 100000 
```

```
/root/.rqalpha/config.yml
Traceback (most recent call last):
  File "/usr/local/bin/rqalpha", line 11, in <module>
    sys.exit(entry_point())
  File "/usr/local/lib/python2.7/dist-packages/rqalpha/__main__.py", line 36, in entry_point
    cli(obj={})
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rqalpha/__main__.py", line 99, in run
    main.run(parse_config(kwargs, config_path))
  File "/usr/local/lib/python2.7/dist-packages/rqalpha/utils/config.py", line 103, in parse_config
    config = load_config(config_path)
  File "/usr/local/lib/python2.7/dist-packages/rqalpha/utils/config.py", line 43, in load_config
    config = config_version_verify(config, config_path)
  File "/usr/local/lib/python2.7/dist-packages/rqalpha/utils/config.py", line 66, in config_version_verify
    config_version = config.get("version", None)
AttributeError: 'NoneType' object has no attribute 'get'
```

在本地生成了空的/root/.rqalpha/config.yml  把这个文件删除后就不会报错了，看样子像是没有生成配置

**Comment by wh1100717** [comment]
@bsknight 这块我们正在重构，下一个版本应该会解决你说的这个问题。

**Comment by wh1100717** [comment]
RQAlpha 2.0.0b0 应该已经解决了这个问题。

您可以通过 `pip install -U rqalpha==2.0.0b0` 来升级试用。
