### ISSUE TITLE
期货日线回测,下订单时因order._init_frozen_cash为nan而异常退出

### ISSUE THREAD

**Issue by baoshuang** [ricequant/rqalpha#736]
# 提 ISSUE 须知

请先阅读文档 [rqalpha文档](http://rqalpha.readthedocs.io/)

如果仍有问题的话请在 [issue列表](https://github.com/ricequant/rqalpha/issues) 中寻找是否有相关问题的解决方案

如果没有的话 麻烦开一个issue 描述以下问题：

## 1. RQAlpha的版本

 4.11.3.dev4.g254ea014

## 2. Python的版本

python 3.8.13

## 3. 是Windows/Linux/MacOS or others?

Windows 10

## 4. 您出现问题对应的源码/或者能复现问题的简易代码 以及对应的配置

```python
import time

from rqalpha import run_func
from rqalpha.apis import *

def init(context):
    logger.info("init")
    context.s1 = "P2301"
    update_universe(context.s1)
    context.fired = False

def before_trading(context):
    """交易日盘前"""
    logger.info("before_trading")
    pass

def handle_bar(context, bar_dict):
    print("handle_bar")
    if not context.fired:
        # buy_open(id_or_ins=context.s1, amount=1)
        submit_order(id_or_ins=context.s1, amount=1, side=SIDE.BUY)  
        context.fired = True


config = {
    "base": {
        "start_date": "2022-05-24",
        "end_date": "2022-09-02",
        "benchmark": None,
        "margin_multiplier": 1,
        "accounts": {
            "Future": 100000
            },
        "run_type": "p",
        'frequency': '1d',
        'forced_liquidation': False,  # 开启后期货账户在爆仓时会被强平。
        },
    "extra": {
        "log_level": "verbose",
        },
    "mod": {
        "sys_accounts": {
            "enabled": True,
            },
        "sys_simulation": {
            "enabled": True,
            "signal": None,

            },
        "sys_progress": {
            "enabled": False,
            },
        "sys_risk": {
            "enabled": False,
            },
        "sys_analyser": {
            "enabled": False,
            "plot": True,
            },
        "sys_scheduler": {
            "enabled": False,
            },
        "sys_transaction_cost": {
            "enabled": True,

            },
        },
    }

run_func(init=init, before_trading=before_trading, handle_bar=handle_bar,  config=config)
```

股票在下单时会设置_init_frozen_cash;期货没有这一步.

## 5. 您出现的错误堆栈日志信息
```
  File "D:\OpenSource\rqalpha\rqalpha\model\order.py", line 268, in init_frozen_cash
    if np.isnan(self._init_frozen_cash):
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

Traceback (most recent call last):
  File "D:\OpenSource\rqalpha\rqalpha\main.py", line 221, in run
    executor.run(bar_dict)
  File "D:\OpenSource\rqalpha\rqalpha\core\executor.py", line 49, in run
    elif event.event_type == EVENT.OPEN_AUCTION:
  File "D:\OpenSource\rqalpha\rqalpha\core\executor.py", line 100, in _split_and_publish
    self._env.event_bus.publish_event(e)
  File "D:\OpenSource\rqalpha\rqalpha\core\events.py", line 47, in publish_event
    if listener(event):
  File "D:\OpenSource\rqalpha\rqalpha\core\strategy.py", line 34, in wrapper
    return func(*args, **kwargs)
  File "D:\OpenSource\rqalpha\rqalpha\core\strategy.py", line 92, in handle_bar
    self._handle_bar(self._user_context, bar_dict)
  File "D:\OpenSource\rqalpha\rqalpha\core\execution_context.py", line 100, in __exit__
    raise user_exc
```

**Comment by Zhou-JiaJun** [comment]
源码未能复现异常，后面继续关注这个问题
